---
format:
  pdf:
    include-in-header:
      - preamble.tex
      - fancyhdr.tex
    fontsize: 10pt
    margin-top: .8in
    margin-bottom: .5in
---

\thispagestyle{empty}

\begin{center}
\textsc{Stat 20: Lab 7.1 Sports} \\
\noindent\rule{12cm}{0.4pt}
\end{center}

**Sport of choice**: _________________

You will find that each sport you can choose from has two data-sets associated with it: a `teams` dataset and a `players` dataset. You can find excerpts of each dataset in a file attached to Ed. You can use these excerpts to answer many of the following questions.

## Question 1
What is the unit of observation for the `teams` data set? What about for the `players` data set?

\   
\   
\   

## Question 2

What is a question you could answer using the `teams` data set but not the `players` data set, and vice versa?

\   
\   
\   
\   
\ 

## Question 3

What is a question that we would need more granular (measured on a finer/more specific part of the game) data than the `teams` and `players` data set provide to answer?

\   
\   
\   
\   

## Question 4
Write out predictive questions (two classification and two regression) that you could answer about your sport using the variables in your `teams` dataset. Identify a response variable for each.

\   
\   
\   
\   
\   
\   
\   


{{< pagebreak >}}

## Question 5

Pick one of your predictive questions you wrote in **Question 4**. Sketch a two-variable plot using the response variable you identified and one other variable in the `teams` data set that could be used to predict it. Title and label your axes, and provide the geometry and aesthetic mapping.


\   
\   
\   
\   
\   
\   
\   
\ 
\   
\   
\   
\ 
\   
\   
\   
\   
\   
\ 
\   
\ 
\   
\   
\   
\   
\   
\   


## Question 6
Consider running a linear regression model to predict your response variable using
the explanatory variable you used in your plot for **Question 5** *and a second* explanatory variable from your `teams` dataset. 
    
What variable would you choose as the second explanatory variable? Which linear model would have the lower $RSS$: the model with one explanatory variable or two? Which model would have the lower $R^2$?

\   
\   
\   
\   
\   
\   
\   
\   



## Question 7
Some people believe analytics is ruining sports because teams are more cautious which makes the games less entertaining. Do you agree or disagree? Why?








