---
title: Roles and Expectations
---

## Tutors

Tutors are the secondary point of contact in the course.

### Roles

Tutors' roles include:

-   Helping with section on MWF
-   Holding office hours
-   Answering questions on the class forum.
-   Assisting with the proctoring of exams.

### Responsibilities:

Tutors' responsibilities include:

-   Attending section
-   Reviewing the day's materials before attending section
-   Within section, fielding and answering student questions during unstructured work time
-   Being present on the class forum during their assigned time.
-   Attending a weekly/biweekly meeting with the instructors

## Readers

### Roles

Readers are the primary graders in the course.

### Responsibilities

Readers are responsible for:

-   Grading their assigned work in a timely manner
-   Resolving regrade requests in a timely manner
-   Attending a weekly/biweekly meeting held by the instructors which is meant to track their progress.


## Instructors/GSI-Instructors

Instructors are the primary point of contact in the course.

### Roles

The roles of instructors include:

-   Designing the course syllabus
-   Leading one, two or three sections on MWF
-   Creating and disseminating course materials. These includes, but are not limited to:
    -   Labs
    -   Problem Sets
    -   In-class slides and handouts
    -   Quizzes and Exams
    -   Review material
    -   (to the tutors) solutions to these course materials
-   Holding office hours
-   Maintaining the course website
-   Answering questions on the class forum.
-   Administering exams
-   Posting final grades.


### Responsibilities

Instructor responsibilities include:

-   Assigning tutors to sections
-   Preparing a general lesson plan for each day of section and disseminating this plan to the tutors by a reasonable time before section
-   Disseminating solutions to in-class handouts, labs and problem sets to tutors by the time of assignment release
-   During class, walking around to groups and assessing their understanding of the material, as well as fielding and answering student questions
-   Creating rubrics for labs
-   Communicating with readers with regards to grading questions
-   Setting up meetings with tutors and readers regularly (weekly or biweekly)
-   Granting assignment extensions
-   Resolving exam conflicts
-   Arranging student accommodations