---
title: 'Minimum Wage'
subtitle: "Lab"
format: stat20handout-pdf
---

In answering the following questions, it will be helpful to consult the data snapshot [AND PAPER EXCERPT?  FIRST 3-4 PAGES?] linked from the Lab 8 webpage.

#### Question 1

State a causal claim about minimum wage and employment levels that might be interesting to test using this dataset.  Identify variables measured in the dataset corresponding to treatment and response for this question.

\
\

#### Question 2

In an ideal world (i.e. one where you have a large budget and/or immense political/administrative power), how you would run a randomized experiment on the  fast-food restaurants in the dataset to test the causal claim in Part I?

\
\

#### Question 3

Pick a few of the measured covariates that seem especially important and sketch a Love plot showing anticipated balance on these variables in the hypothetical randomized experiment from Question 2.

\
\
\
\

#### Question 4

Now consider the actual observational study. Sketch a Love plot showing anticipated balance on the covariates from Question 3 between restaurants in New Jersey and restaurants in Pennsylvania and explain any differences fro the sketch in Question 3.

\
\
\

#### Question 5

What does it mean to create a matched comparison between New Jersey and Pennsylvania restaurants?  Sketch a Love plot showing balance after matching.

\
\
\
\
\
\
\
\
\



#### Question 6

	What assumptions are needed to trust the matched estimate that we don’t require for the hypothetical randomized trial in Question 2?  Based on the description of the data, do you believe those assumptions? Why or why not?

\
\
\
\
\

{{< pagebreak >}}

#### Question 7

Now consider the data from both survey waves. Sketch a line plot showing how you anticipate employment levels change between the two waves for New Jersey restaurants and for Pennsylvania restaurants.



\
\
\
\
\
\
\
\

#### Question 8

Describe how to construct a pre/post estimate using the 
New Jersey data alone.  What assumptions are needed here and how do they compare to those for the matched estimator and the randomized trial?  Are they plausible?

\
\
\
\
\
\
\
\
\
\
\
\
\
\

{{< pagebreak >}}

#### Question 9

Describe how to construct a difference-in-difference estimate
using the full dataset.  How are the assumptions it requires different from those for the other designs discussed in the previous questions?  Which approach do you believe will be most useful in practice for testing the original causal claim?



\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
