project:
  output-dir: "_full-site"
  render:
    - "docs"
  
metadata-files:
  - "adaptive-nav.yml"

# Modify aesthetics and add Guide to navbar
website:
  title: "Stat 20 Staff Site"
  open-graph:
    site-name: "Stat 20 Staff Site"
  navbar:
    background: warning
    right:
      - text: "Staff Guide"
        href: staff-guide/index.qmd
      - text: "Docs"
        href: docs/index.qmd

        
        