---
format:
  pdf:
    include-in-header:
      - preamble.tex
      - fancyhdr.tex
    fontsize: 10pt
    margin-top: .8in
    margin-bottom: .5in
---

\thispagestyle{empty}

\begin{center}
\textsc{Stat 20: Lab 5.1: People's Park} \\
\noindent\rule{12cm}{0.4pt}
\end{center}

In answering the following questions, it will be helpful to consult

1. the email from Chancellor Christ,
2. the description of the background and methodology, and
3. the original questionnaire.

Based on your interpretation of these documents, address the following questions.

#### Question 1

What was the goal(s) of the Chancellor's office in commissioning this survey?

\
\

#### Question 2

What is the population from which the Chancellor's office has drawn their sample?

\
\

#### Question 3

Describe two population parameters that the Chancellor's office is trying to estimate using the survey data.

\
\

#### Question 4

What was initial sample size of students selected to take the survey? What was the final sample size that actually did? What was the response rate?

\
\

#### Question 5

Describe one scenario wherein this response rate would lead to results that they could not generalize from the sample to the population. Be specific.

\
\

#### Question 6

Consider the type of data collected in question 8, which is measured using the Likert Scale. Review the Wikipedia article on the Likert Scale (particularly the Scoring and Analysis section) to determine: Where does this type of data fall in the Data Taxonomy? 

\

#### Question 7

Sketch a data frame of what the first 5 rows of the data frame might look like that contains the responses from the first 5 students. Include columns showing what the data might look like that comes out of questions 1, 7, and 8. Note that in the data set, the data values are all translated from words into numbers. Speculate as to how this translation is done.

\
\
\
\
\
\
\
\
\
\
\
\
\
\


#### Question 8

Sketch a plot of what the data might look like that is generated by each of the following survey questions. Note that this should be done without looking at the actual data frame.
    a. Question 9
    b. Question 10
    c. Question 18 and 21 (showing the change from before and after the information)

