---
title: "Problem Set 6"
subtitle: "Due Monday, November 21"
---

# Questions

## Question 1

In order to study gender bias in promotion decisions, researchers took 48 resumes and randomly assigned them to 48 bank managers who were asked whether they would promote this candidate or not. The resumes were identical except the name: 24 of them had names generally associated with women, 24 of them had names generally associated with men. The data from this study can be found in the `promote` data frame. Use this data to determine whether gender played a role in promotion decisions.

The `promote` dataset can be found in the `stat20data` library.

Let your significance level $\alpha = 0.01$.

### part a

Write the null and alternative hypothesis.

### part b

Compute the observed test statistic.

### part c

Visualize the observed data using an appropriate plot.

### part d

Construct a plot featuring 9 subplots, each one featuring a visualization of a data set generated under the null hypothesis. Does your visualization of the observed data from the previous part look like it could be one of these plots?

### part e

Construct and save the null distribution of statistics.

### part f

Visualize the null distribution.

### part g

Compute the p-value.

### part h

Interpret your p-value based on the significance level we set at the beginning of the problem.\
\
What does it say about the consistency between the null hypothesis and the observed data?

### part i

What is the probability that we conclude that there is a difference in promotion decisions by gender when in truth there is no difference?

### part j

There are 48 bank managers who participated in this experiment. Imagine we increase double the number of managers, so that there are 96 bank managers; 46 who receive resumes with names generally associated with women, 46 of them who receive resumes with had names generally associated with men.

What would happen to the power of your hypothesis test?

## Question 2

Instead of conducting a hypothesis test concerning the difference in these proportions from **Question 1**, form a confidence interval for your estimate (what had been your observed test statistic). Use the bootstrap to form a 95% confidence interval for this statistic. Does it contain 0? How is this related to the result from question 1?

## Question 3

For each of the following sets of hypotheses, determine whether committing a Type I error or a Type II error has greater real-world consequences. Explain your decision.

### part a

Imagine that the San Francisco Giants hold a book donation promotion for one of their games where every individual who brings a used book to the stadium is allowed free entry.

$H_0$: The number of individuals who wish attend the game will be no more than the capacity of the stadium.

$H_A$: The number of individuals who wish to attend the game will exceed the capacity of the stadium.

### part b

$H_0$: A new operating system is **no more effective** for Carbon Health to use on the computers at its clinics than the old operating system.

$H_A$: A new operating system is **more effective** for Carbon Health to use on the computers at its clinics than the old operating system.

### part c

$H_0$: The results of the 2020 United States presidential election were **legitimate** (the right candidate won).

$H_A$: The results of the 2020 United States presidential election were **fraudulent** (the wrong candidate won).

## Questions 4 and 5

For the following two questions below do the following:

-   Who is the target audience? What is the communication medium? What is the goal the communication is trying to accomplish?

-   Discuss how each of the four principles for effective communication are or are not used.

-   Discuss how each of the strategies for effective communication are or are not used.

-   Are there ways to improve how the content was communicated?

#### Question 4: stat20 website

Critique our course website, [www.stat20.org/](https://www.stat20.org/) (either the whole website or a specific part e.g. one set of notes/slides, etc).

### Question 5: a data visualization

Any data visualization. Could be something in our course or anywhere else. Some suggestions\
\

-   Check out [Flowing data](https://flowingdata.com/made-by-flowingdata/), for example

    -   [Where bars out number grocery stores](https://flowingdata.com/2014/05/29/bars-versus-grocery-stores-around-the-world/)

    -   [Commonnness of Divorce in America](https://flowingdata.com/2022/06/07/commonness-of-divorce-in-america/)

    -   [Life satisfaction and age](https://flowingdata.com/2022/11/10/life-satisfaction-and-age/)

    -   [Rhythm of food](https://rhythm-of-food.net/)
