---
title: "A Grammar of Graphics"
subtitle: "WS"
format: stat20handout-typst
---

## Question 1

Use the `gapminder` data set in the `gapminder` library to recreate a version of Hans Rosling's famous data visualization shown in the *A Grammar of Graphics* slides (a single plot instead of a movie; in other words, for just a single year). 

-   You can see at a glance which years are available by running `count(gapminder, year)` in an R chunk. 

-   In place of fertility rate use GDP per capita.

Constructing this plot requires several distinct steps.

1. Determine the correct geometry for the plot and make an initial `ggplot` with the two variables on the x and y axis.

2. Distinguish the continents by either shape or color. Which ever one you do not use, *set* its value to something other than the default. *Hint: use the help_file for `geom_point()` to find options you can set to!*

3. Alter the x and y axis labels so that they're more descriptive than just the variable given names in `gapminder`. 

4. Add an annotation that draws attention to a particular feature of the data (of your choosing).

5. Title your plot with a claim based on your data. 

6. Apply a theme of your choosing.

Use RStudio to write the code and see your visualization. Once you are happy with it, handwrite your code in the space below.


{{< pagebreak >}}

## Question 2

Revisit one of the plots that you created for the Class Survey Lab, but incorporate at least 2 of the elements from the Communicating with Graphics section of the Grammar of Graphics tutorial to polish your plot into one that tells a more focused story. No need to copy that code here but in the space below write a list of the elements that you applied to each plot.

