{
  "hash": "be54716d0822f989fa7577dfbbc3c723",
  "result": {
    "markdown": "---\ntitle: \"Multiple Linear Regression\"\nsubtitle: \"Summarizing linear relationships in high dimensions\"\ndate: 02/18/23\n---\n<!-- The bit before that is commented out adds publish date to document metadata and button links at the top of the doc. This workflow can be revisited but currently doesn't work because listings aren't updated with these dates, only the renderd docs. -->\n\n::: {.cell}\n\n:::\n\n\n\n[[Discuss]{.btn .btn-primary}](https://edstem.org/us/courses/31657) [[Reading Questions]{.btn .btn-primary}](https://www.gradescope.com/courses/477232) [[PDF]{.btn .btn-primary}](notes.pdf)\n\n\n\n\\\n\n[I]{.dropcap}n the last lecture we built our first linear model: an equation of a line drawn through the scatter plot.\n\n$$ \\hat{y} = 96.2 + -0.89 x $$\n\nWhile the idea is simple enough, there is a sea of terminology that floats around this method. A *linear model* is any model that explains the $y$, often called the *response variable* or *dependent variable*, as a linear function of the $x$, often called the *explanatory variable* or *independent variable*. There are many different methods that can be used to decide which line to draw through a scatter plot. The most commonly-used approach is called the *method of least squares*, a method we'll look at closely when we turn to prediction. If we zoom out, a linear model fit by least squares is an example of a *regression model*, which refers to any model (linear or non-linear) used to explain a numerical response variable.\n\nThe reason for all of this jargon isn't purely to infuriate students of statistics. Linear models are one of the most widely used statistical tools; you can find them in used in diverse fields like biology, business, and political science. Each field tends to adapt the tool and the language around them to their specific needs.\n\nA reality of practicing statistics in these field, however, is that most data sets are more complex than the example that we saw in the last notes, where there were only two variables. Most phenomena have many different variables that relate to one another in complex ways. We need a more more powerful tool to help guide us into these higher dimensions.\n\n## Scatterplots of three variables\n\nIn studying the Grammar of Graphics, we learned how Hans Rosling's Gapminder visualization used location along the x, location along the y, color, size, and time to encode not just two but *five* different data dimensions in his scatter plot. We start with a more modest goal. Let's build a scatter plot - and a corresponding linear model - that summarizes data in three variables, and let's turn to a data set not from public health but the world of food.\n\n:::{.column-margin}\n![Hans Rosling's Gapminder visualization](images/gapminder.png)\n:::\n\nThe Zagat Guide was for many years the authoritative source of restaurant reviews. Their approach was very different from Yelp!. Zagat's review of a restaurant was compiled by a professional restaurant reviewer who would visit a restaurant and rate it on a 30 point scale across three categories: food, decor, and service. They would also note the average price of a meal and write up a narrative review.\n\nHere's an example of a review from an Italian restaurant called Marea in New York City.\n\n![](images/zagat.png){fig-alt=\"A picture of a Zagat review of the Italian restaurant Marea in New York City, with scores on food, decor, and service along with quotations from the narrative review.\" width=\"400\" fig-align=\"center\"}\n\nIn addition to learning about the food scores (27), and getting some helpful tips (\"bring your bank manager\"), we see they've also recorded a few more variables on this restaurant: the phone number and website, their opening hours, and the neighborhood (Midtown).\n\n### Two numerical, one categorical\n\nWhat is the relationship between the food quality and the price of a meal at Italian restaurant? Are these two variables positively correlated or is the best Italian meal in New York a simple and inexpensive slice of pizza?\n\nTo answer these questions, we need more data. The data frame below contains Zagat reviews from 168 Italian restaurants in Manhattan.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nzagat <- read_csv(\"https://www.dropbox.com/s/c797oanmvdzjegt/zagat.csv?dl=1\")\nzagat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 168 × 6\n   restaurant          price  food decor service geo  \n   <chr>               <dbl> <dbl> <dbl>   <dbl> <chr>\n 1 Daniella Ristorante    43    22    18      20 west \n 2 Tello's Ristorante     32    20    19      19 west \n 3 Biricchino             34    21    13      18 west \n 4 Bottino                41    20    20      17 west \n 5 Da Umberto             54    24    19      21 west \n 6 Le Madri               52    22    22      21 west \n 7 Le Zie                 34    22    16      21 west \n 8 Pasticcio              34    20    18      21 east \n 9 Belluno                39    22    19      22 east \n10 Cinque Terre           44    21    17      19 east \n# … with 158 more rows\n```\n:::\n:::\n\n\nApplying the taxonomy of data, we see that for each restaurant we have recorded the price of an average meal, the food, decor, and service scores (all numerical variables) as well as a note regarding geography (a categorical nominal variable). `geo` captures whether the restaurant is located on the east side or the west side of Manhattan[^geo].\n\n[^geo]: Fifth Avenue is the wide north-south street that divides Manhattan into an east side and a west side.\n\nLet's summarize the relationship between food quality, price, and one categorical variable - geography - using a colored scatter plot.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nzagat %>%\n  ggplot(aes(x = food,\n             y = price,\n             color = geo)) +\n  geom_jitter() +\n  theme_bw() +\n  labs(x = \"Food Quality\",\n       y = \"Price of Average Meal\",\n       color = \"Geography\")\n```\n\n::: {.cell-output-display}\n![](notes_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=480}\n:::\n:::\n\n\nIt looks like if you want a very tasty meal, you'll have to pay for it. There is a moderately strong, positive, and linear relationship between food quality and price. This plot, however, has a third variable in it: geography. The restaurants from the east and west sides are fairly well mixed, but to my eye the points on the west side might be a tad bit lower on price than the points from the east side. I could numerically summarize the relationship between these three variables by hand-drawing two lines, one for each neighborhood.\n\n![](images/zagat-handdrawn.png){fig-align=\"center\" width=\"450\"}\n\nFor a more systematic approach for drawing lines through the center of scatter plots, we need to return to the method of least squares, which is done in R using `lm()`. In this linear model, we wish to explain the $y$ variable as a function of two explanatory variables, `food` and `geo`, both found in the `zagat` data frame. We can express that relationship using the formula notation.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nm1 <- lm(price ~ food + geo, zagat)\nm1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = price ~ food + geo, data = zagat)\n\nCoefficients:\n(Intercept)         food      geowest  \n    -15.970        2.875       -1.459  \n```\n:::\n:::\n\n\nIt worked . . . or did it? If extend our reasoning from the last notes, we should write this model as\n\n$$\\widehat{price} = -15.97 + 2.87 \\times food - 1.45 \\times geowest$$\n\nWhat does it mean to put a categorical variable, `geo`, into a linear model? And how do three three numbers translate into the two lines shown above?\n\n#### Dummy variables\n\nWhen working with linear models like the one above, the value of the explanatory variable, $geowest$, is multiplied by a slope, 1.45. According to the Taxonomy of Data, arithmetic functions like multiplication are only defined for numerical variables. While that would seem to rule out categorical variables for use as explanatory variables, statisticians have come up with a clever work-around: the dummy variable.\n\n**Dummy Variable**\n: A logical variable that is true if an observation takes a particular level of a categorical variable and false otherwise. A categorical variable with $k$ levels can be encoded using $k-1$ dummy variables.\n\nThe categorical variable `geo` can be converted into dummy variable by shifting the question from \"Which side of Manhattan are you on?\" to \"Are you on the west side of Manhattan?\" This is a `mutate` step.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nzagat %>%\n  mutate(geowest = geo == \"west\") %>%\n  select(food, price, geo, geowest)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 168 × 4\n    food price geo   geowest\n   <dbl> <dbl> <chr> <lgl>  \n 1    22    43 west  TRUE   \n 2    20    32 west  TRUE   \n 3    21    34 west  TRUE   \n 4    20    41 west  TRUE   \n 5    24    54 west  TRUE   \n 6    22    52 west  TRUE   \n 7    22    34 west  TRUE   \n 8    20    34 east  FALSE  \n 9    22    39 east  FALSE  \n10    21    44 east  FALSE  \n# … with 158 more rows\n```\n:::\n:::\n\n\nThe new dummy variable `geowest` is a *logical* variable, so it has a dual representation as TRUE/FALSE as well as 1/0. Previously, this allowed us to do Boolean algebra. Here, it allows us to include a dummy variable in a linear model.\n\nWhile you can create dummy variables by hand using `mutate`, they are created automatically whenever you put a categorical variable into `lm()`. Let's revisit the linear model that we fit above.\n\n$$\\widehat{price} = -15.97 + 2.87 \\times food - 1.45 \\times geowest$$\n\nTo understand the geometry of this model, let's focus on what the fitted values will be for any restaurant that is on the west side. For those restaurants, the `geowest` dummy variable will take a value of 1, so if we plug that in and rearrange,\n\n\\begin{eqnarray}\n\\widehat{price} &= -15.97 + 2.87 \\times food - 1.45 \\times 1 \\\\\n &= (-15.97 - 1.45) + 2.87 \\times food \\\\\n &= -17.42 + 2.87 \\times food\n\\end{eqnarray}\n\nThat is a familiar sight: that is an equation for a line.\n\nLet's repeat this process for the restaurants on the east side, where the `geowest` dummy variable will take a value of 0.\n\n\\begin{eqnarray}\n\\widehat{price} &= -15.97 + 2.87 \\times food - 1.45 \\times 0 \\\\\n &= -15.97 + 2.87 \\times food\n\\end{eqnarray}\n\nThat is also the equation for line.\n\nIf you look back and forth between these two equations, you'll notice that they share the same slope and have different y-intercepts. Geometrically, this means that the output of `lm()` was describing the equation of *two parallel lines*. That means we can use the output of `lm()` to replace my hand-drawn lines with ones that arise from the method of least squares.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nzagat <- zagat %>%\n  mutate(y_hat = fitted(m1))\n\n# We use geom_line instead of geom_abline since the model\n# now has two slope coefficients\np_parallel <- zagat %>%\n  ggplot(aes(x = food,\n             y = price,\n             color = geo)) +\n  geom_jitter() +\n  theme_bw() +\n  labs(x = \"Food Quality\",\n       y = \"Price of Average Meal\",\n       color = \"Geography\") +\n  geom_line(aes(y = y_hat))\n\np_parallel\n```\n\n::: {.cell-output-display}\n![](notes_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n\n### Multiple Linear Regression\n\nThe model that we fit that explains the price of a meal in terms the food rating and the geography is our first example of a *multiple linear regression model*.\n\n**Multiple Linear Regression**\n:    A method of explaining a continuous numerical $y$ variable in terms of a linear function of $p$ explanatory variables, $x_i$, which can be numerical or dummy variables.\n     $$ \\hat{y} = b_0 + b_1 x_1 + b_2 x_2 + \\ldots b_p x_p $$\n     Each of the $b_i$ are called *coefficients*.\n     \nTo fit a muliple linear regression model using least squares in R, you can use the `lm()` function, which each additional explanatory variable separated by a `+`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlm(y ~ x_1 + x_2 + x_3 ... x_p, data)\n```\n:::\n\n\nMultiple linear regression is powerful because it has no limit to the number of variables that we can include in the model. While Hans Rosling was able to fit 5 variables into a single graphic, what if we had 10 variables? Multiple linear regression allows us to understand high dimensional linear relationships beyond whats possible using our visual system.\n\nTo build intuition around how to interpret these higher dimensional models, let's look at a model that we can visualize: one with two numerical explanatory variables.\n\n### Three numerical\n\nWhile the standard scatter plot allows us to understand the association between two numerical variables like `price` and `food`, to understand the relationship between three numerical variables, we will need to build this scatterplot in 3D[^plotly].\n\n[^plotly]: While `ggplot2` is the best package for static statistical graphics, it does not have any interactive functionality. This plot was made using a system called `plotly`, which can be used both in R and Python. Read more about how it works at <https://plotly.com/r/>.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(plotly)\nlibrary(reshape2)\n\nm1 <- lm(price ~ food + decor, data = zagat)\ngrid_points <- 30\naxis_x <- seq(min(zagat$food), \n              max(zagat$food),\n              length.out = grid_points)\naxis_y <- seq(min(zagat$decor), \n              max(zagat$decor),\n              length.out = grid_points)\nzagat_plane <- expand.grid(food = axis_x, \n                         decor = axis_y, \n                         KEEP.OUT.ATTRS = F)\nzagat_plane$price <- predict.lm(m1, newdata = zagat_plane)\nz <- acast(zagat_plane, food ~ decor, value.var = \"price\")\np <- plot_ly(zagat, x = ~food, y = ~decor, z = ~price, showlegend=FALSE) %>%\n  add_markers(marker = list(size = 5,\n                            opacity = .6,\n                            color = \"steelblue\"),\n              name = ~restaurant) %>%\n  config(displayModeBar = FALSE) \np\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-54ea6207ff0877834ca7\" style=\"width:100%;height:650px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-54ea6207ff0877834ca7\">{\"x\":{\"visdat\":{\"1ce9449fd7e6\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"1ce9449fd7e6\",\"attrs\":{\"1ce9449fd7e6\":{\"x\":{},\"y\":{},\"z\":{},\"showlegend\":false,\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"size\":5,\"opacity\":0.6,\"color\":\"steelblue\"},\"name\":{},\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"xaxis\":{\"title\":\"food\"},\"yaxis\":{\"title\":\"decor\"},\"zaxis\":{\"title\":\"price\"}},\"hovermode\":\"closest\",\"showlegend\":false},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false,\"displayModeBar\":false},\"data\":[{\"x\":[19],\"y\":[15],\"z\":[33],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Amarone\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Anche Vivolo\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[18],\"y\":[17],\"z\":[33],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Andiamo\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[41],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Arno\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[20],\"y\":[19],\"z\":[44],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Artusi\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[17],\"y\":[15],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Baci\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[17],\"y\":[18],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Baraonda\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[16],\"y\":[16],\"z\":[44],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Barbaresco\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[20],\"y\":[23],\"z\":[52],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Barbetta\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[18],\"y\":[13],\"z\":[24],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Bardolino\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[18],\"y\":[15],\"z\":[32],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Basta Pasta\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[20],\"y\":[17],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Becco\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Bella Luna\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[22],\"y\":[21],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Bellini\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[21],\"y\":[17],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Bello\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[22],\"y\":[19],\"z\":[39],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Belluno\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[21],\"y\":[20],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Bice\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[21],\"y\":[13],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Biricchino\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[20],\"y\":[17],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Bond� Ristorante�\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[20],\"y\":[20],\"z\":[41],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Bottino\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[22],\"y\":[17],\"z\":[56],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Bravo Gianni\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[22],\"y\":[19],\"z\":[50],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Bruno Ristorante\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[23],\"y\":[19],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Cafe Trevi\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[18],\"y\":[17],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Caffe Cielo\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Caffe Grazie\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[24],\"y\":[21],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Campagna\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[24],\"y\":[20],\"z\":[53],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Campagnola\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[22],\"y\":[17],\"z\":[44],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Canaletto\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[19],\"y\":[15],\"z\":[29],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Cara Mia\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[19],\"y\":[13],\"z\":[30],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Carino Ristorante\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[33],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Casa Di Meglio\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[20],\"y\":[19],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Casa Mia\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[21],\"y\":[18],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Castellano\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[22],\"y\":[20],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Cellini\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[20],\"y\":[16],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Chianti\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[19],\"y\":[19],\"z\":[40],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Ciao Europa\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[21],\"y\":[17],\"z\":[44],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Cinque Terre\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[22],\"y\":[24],\"z\":[53],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Circo Osteria del\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[22],\"y\":[21],\"z\":[55],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Coco Pazzo\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[20],\"y\":[19],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Coco Pazzo Caf�\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[18],\"y\":[18],\"z\":[47],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Coco Pazzo Teatro\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[19],\"y\":[16],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Cucina Vivolo\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[22],\"y\":[19],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Da Antonio Ristorante\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[20],\"y\":[18],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Da Filippo\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[21],\"y\":[16],\"z\":[42],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Da Tommaso\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[24],\"y\":[19],\"z\":[54],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Da Umberto\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[22],\"y\":[18],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Daniella Ristorante\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[23],\"y\":[22],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"DeGrezia\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[19],\"y\":[15],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Divino Ristorante\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[22],\"y\":[18],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Due\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[20],\"y\":[20],\"z\":[40],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"East River Cafe\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[18],\"y\":[15],\"z\":[25],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Ecco-la\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[23],\"y\":[18],\"z\":[50],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Elio's\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[23],\"y\":[20],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Enoteca i Trulli\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[25],\"y\":[24],\"z\":[54],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Erminia\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[16],\"y\":[15],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Ernie's\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[25],\"y\":[22],\"z\":[62],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"FELIDIA\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Fino\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[21],\"y\":[19],\"z\":[41],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Firenze\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[23],\"y\":[20],\"z\":[48],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Follonico\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[19],\"y\":[18],\"z\":[39],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Fred's at Barneys NY\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[23],\"y\":[21],\"z\":[50],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Fresco by Scotto\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[22],\"y\":[19],\"z\":[50],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Gabriel's\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[24],\"y\":[10],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Gennaro\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[21],\"y\":[18],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Giambelli\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[20],\"y\":[14],\"z\":[41],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Gino\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[22],\"y\":[19],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Giovanni\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[21],\"y\":[18],\"z\":[48],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Giovanni Venticinque\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[21],\"y\":[18],\"z\":[50],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Girasole\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[35],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Grace's Trattoria\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[23],\"y\":[20],\"z\":[54],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Grifone\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[21],\"y\":[20],\"z\":[65],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Harry Cipriani\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[23],\"y\":[22],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"I Trulli\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[20],\"y\":[15],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Il Gatto & La Volpe\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[22],\"y\":[19],\"z\":[52],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Il Menestrello\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[23],\"y\":[20],\"z\":[55],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Il Monello\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[24],\"y\":[20],\"z\":[57],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Il Nido\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[24],\"y\":[21],\"z\":[57],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Il Postino\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[21],\"y\":[16],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Il Riccio\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[23],\"y\":[19],\"z\":[57],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Il Tinello\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[17],\"y\":[14],\"z\":[36],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Il Vagabondo\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[21],\"y\":[20],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Il Valentino\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[21],\"y\":[17],\"z\":[56],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Il Valletto Due Mila\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[19],\"y\":[18],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Joanna's\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[20],\"y\":[16],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"La Gioconda\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[21],\"y\":[15],\"z\":[42],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"La Grolla, Ristorante\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[19],\"y\":[16],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"La Rivista\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[18],\"y\":[9],\"z\":[19],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Lamarca\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[22],\"y\":[22],\"z\":[52],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Le Madri\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[22],\"y\":[16],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Le Zie\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[19],\"y\":[18],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Limoncello\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[21],\"y\":[15],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Luca\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[20],\"y\":[19],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Lumi\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Luna Blu\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[33],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Luna Piena\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[24],\"y\":[20],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Lusardi's\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[17],\"y\":[14],\"z\":[29],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Mangia e Bevi\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[21],\"y\":[19],\"z\":[47],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Marchi's\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[19],\"y\":[14],\"z\":[33],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Maruzzella\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[18],\"y\":[15],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Mediterraneo\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[19],\"y\":[15],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Mezzaluna\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[22],\"y\":[17],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"M�tisse\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[23],\"y\":[17],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Nanni's\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[54],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Nello\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[21],\"y\":[19],\"z\":[52],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Nicola Paone\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[22],\"y\":[18],\"z\":[50],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Nicola's\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[23],\"y\":[20],\"z\":[52],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Nino's\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[21],\"y\":[19],\"z\":[39],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Nocello\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[35],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Notaro\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[23],\"y\":[19],\"z\":[47],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Novit�\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[22],\"y\":[18],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Orso\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[20],\"y\":[18],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Osteria Laguna\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[20],\"y\":[17],\"z\":[40],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Osteria al Doge\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[22],\"y\":[25],\"z\":[63],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Palio\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[23],\"y\":[19],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Paola's\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Paper Moon Milano\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Pappardella\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[22],\"y\":[16],\"z\":[47],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Parma\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[20],\"y\":[18],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Pasticcio\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[20],\"y\":[16],\"z\":[42],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Patsy's\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[19],\"y\":[16],\"z\":[40],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Paul & Jimmy's\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[20],\"y\":[15],\"z\":[32],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Pietrasanta\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[20],\"y\":[17],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Pomodoro Rosso\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[24],\"y\":[22],\"z\":[60],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Primavera\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[23],\"y\":[17],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Primola\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[20],\"y\":[16],\"z\":[26],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Puccini\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[19],\"y\":[15],\"z\":[32],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Puttanesca\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[41],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Quattro Gatti\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[19],\"y\":[23],\"z\":[65],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Rainbow Grill\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[23],\"y\":[16],\"z\":[57],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Rao's\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[23],\"y\":[23],\"z\":[52],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Remi\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[36],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Ribollita\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[20],\"y\":[14],\"z\":[23],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Rino Trattoria\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[20],\"y\":[18],\"z\":[47],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Rossini's\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[23],\"y\":[19],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Rughetta\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Sal Anthony's\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[19],\"y\":[16],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Sambuca, Trattoria\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[23],\"y\":[22],\"z\":[65],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"San Domenico\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[22],\"y\":[20],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"San Giusto\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[24],\"y\":[21],\"z\":[58],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"San Pietro\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[21],\"y\":[19],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Scaletta\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[24],\"y\":[18],\"z\":[58],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Scalinatella\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[21],\"y\":[16],\"z\":[48],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Sette Mezzo\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[18],\"y\":[21],\"z\":[42],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Sette MoMA\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[23],\"y\":[16],\"z\":[36],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Sirabella's\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[23],\"y\":[19],\"z\":[54],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Sistina\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[19],\"y\":[18],\"z\":[39],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Spada\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[17],\"y\":[14],\"z\":[28],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Supreme Macaroni Co.\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[20],\"y\":[19],\"z\":[32],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Tello's Ristorante\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[21],\"y\":[17],\"z\":[41],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Teodora\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[20],\"y\":[18],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Tino's\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[19],\"y\":[14],\"z\":[30],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Tony's Di Napoli\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[19],\"y\":[21],\"z\":[47],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Torre di Pisa\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[21],\"y\":[19],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Trattoria Alba\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[21],\"y\":[18],\"z\":[29],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Trattoria Del Sogno\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[17],\"y\":[16],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Trattoria Dopo Teatro\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[20],\"y\":[16],\"z\":[35],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Trattoria Rustica\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[20],\"y\":[16],\"z\":[33],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Triangolo\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[20],\"y\":[17],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Trionfo\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[19],\"y\":[20],\"z\":[40],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Tuscan Square\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[22],\"y\":[21],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Vago Ristorante\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[21],\"y\":[6],\"z\":[22],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Veronica\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[22],\"y\":[17],\"z\":[40],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Via Oreto\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[22],\"y\":[22],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"ViceVersa\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[20],\"y\":[15],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Vico\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[22],\"y\":[18],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Villa Berulia\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[20],\"y\":[19],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Vivolo\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[17],\"y\":[14],\"z\":[29],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Zucchero e Pomodori\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n\n```{.r .cell-code}\n# %>%\n#   add_surface(x = axis_x, \n#               y = axis_y, \n#               z = z, showscale=FALSE,\n#               colorscale = list(c(0, 1), c(\"tan\", \"tan\")),\n#               name = \"Linear Model\")\n```\n:::\n\n\nTake a moment to explore this scatter plot. Can you find the name of the restaurant with very bad decor but pretty good food and a price to match? (It's Gennaro.) What about the restaurant that equally bad decor but has rock bottom prices that's surprising given it's food quality isn't actually somewhat respectable? (It's Lamarca.)\n\nInstead of depicting the relationship between these three variables graphically, let's do it numerically by fitting a linear model.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nm2 <- lm(price ~ food + decor, data = zagat)\nm2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = price ~ food + decor, data = zagat)\n\nCoefficients:\n(Intercept)         food        decor  \n    -24.500        1.646        1.882  \n```\n:::\n:::\n\n\nWe can write the corresponding equation of the model as\n\n$$ \\widehat{price} = -24.5 + 1.64 \\times food + 1.88 \\times decor $$\n\nTo understand the geometry of this model, we can't use the trick that we did with dummy variables. `decor` is a numerical variable just like `food`, so it takes more values than just 0 and 1.\n\nIndeed this linear model is describing a *plane*.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np %>%\n  add_surface(x = axis_x,\n              y = axis_y,\n              z = z, showscale=FALSE,\n              colorscale = list(c(0, 1), c(\"tan\", \"tan\")),\n              name = \"Linear Model\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-05ce0aea305519339e4e\" style=\"width:100%;height:650px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-05ce0aea305519339e4e\">{\"x\":{\"visdat\":{\"1ce9449fd7e6\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"1ce9449fd7e6\",\"attrs\":{\"1ce9449fd7e6\":{\"x\":{},\"y\":{},\"z\":{},\"showlegend\":false,\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"size\":5,\"opacity\":0.6,\"color\":\"steelblue\"},\"name\":{},\"inherit\":true},\"1ce9449fd7e6.1\":{\"x\":[16,16.3103448275862,16.6206896551724,16.9310344827586,17.2413793103448,17.551724137931,17.8620689655172,18.1724137931034,18.4827586206897,18.7931034482759,19.1034482758621,19.4137931034483,19.7241379310345,20.0344827586207,20.3448275862069,20.6551724137931,20.9655172413793,21.2758620689655,21.5862068965517,21.8965517241379,22.2068965517241,22.5172413793103,22.8275862068966,23.1379310344828,23.448275862069,23.7586206896552,24.0689655172414,24.3793103448276,24.6896551724138,25],\"y\":[6,6.6551724137931,7.31034482758621,7.96551724137931,8.62068965517241,9.27586206896552,9.93103448275862,10.5862068965517,11.2413793103448,11.8965517241379,12.551724137931,13.2068965517241,13.8620689655172,14.5172413793103,15.1724137931034,15.8275862068966,16.4827586206897,17.1379310344828,17.7931034482759,18.448275862069,19.1034482758621,19.7586206896552,20.4137931034483,21.0689655172414,21.7241379310345,22.3793103448276,23.0344827586207,23.6896551724138,24.3448275862069,25],\"z\":[[13.1303263354812,14.3633707595381,15.596415183595,16.829459607652,18.0625040317089,19.2955484557659,20.5285928798228,21.7616373038797,22.9946817279367,24.2277261519936,25.4607705760505,26.6938150001075,27.9268594241644,29.1599038482214,30.3929482722783,31.6259926963352,32.8590371203922,34.0920815444491,35.3251259685061,36.558170392563,37.7912148166199,39.0242592406769,40.2573036647338,41.4903480887908,42.7233925128477,43.9564369369046,45.1894813609616,46.4225257850185,47.6555702090755,48.8886146331324],[13.6412003024677,14.8742447265247,16.1072891505816,17.3403335746386,18.5733779986955,19.8064224227524,21.0394668468094,22.2725112708663,23.5055556949232,24.7386001189802,25.9716445430371,27.2046889670941,28.437733391151,29.6707778152079,30.9038222392649,32.1368666633218,33.3699110873788,34.6029555114357,35.8359999354926,37.0690443595496,38.3020887836065,39.5351332076635,40.7681776317204,42.0012220557773,43.2342664798343,44.4673109038912,45.7003553279482,46.9333997520051,48.166444176062,49.399488600119],[14.1520742694543,15.3851186935113,16.6181631175682,17.8512075416251,19.0842519656821,20.317296389739,21.5503408137959,22.7833852378529,24.0164296619098,25.2494740859668,26.4825185100237,27.7155629340806,28.9486073581376,30.1816517821945,31.4146962062515,32.6477406303084,33.8807850543653,35.1138294784223,36.3468739024792,37.5799183265361,38.8129627505931,40.04600717465,41.279051598707,42.5120960227639,43.7451404468209,44.9781848708778,46.2112292949347,47.4442737189917,48.6773181430486,49.9103625671055],[14.6629482364409,15.8959926604978,17.1290370845548,18.3620815086117,19.5951259326686,20.8281703567256,22.0612147807825,23.2942592048395,24.5273036288964,25.7603480529533,26.9933924770103,28.2264369010672,29.4594813251242,30.6925257491811,31.925570173238,33.158614597295,34.3916590213519,35.6247034454088,36.8577478694658,38.0907922935227,39.3238367175797,40.5568811416366,41.7899255656936,43.0229699897505,44.2560144138074,45.4890588378644,46.7221032619213,47.9551476859782,49.1881921100352,50.4212365340921],[15.1738222034275,16.4068666274844,17.6399110515413,18.8729554755983,20.1059998996552,21.3390443237122,22.5720887477691,23.805133171826,25.038177595883,26.2712220199399,27.5042664439969,28.7373108680538,29.9703552921107,31.2033997161677,32.4364441402246,33.6694885642816,34.9025329883385,36.1355774123954,37.3686218364524,38.6016662605093,39.8347106845662,41.0677551086232,42.3007995326801,43.5338439567371,44.766888380794,45.9999328048509,47.2329772289079,48.4660216529648,49.6990660770218,50.9321105010787],[15.684696170414,16.917740594471,18.1507850185279,19.3838294425849,20.6168738666418,21.8499182906987,23.0829627147557,24.3160071388126,25.5490515628695,26.7820959869265,28.0151404109834,29.2481848350404,30.4812292590973,31.7142736831542,32.9473181072112,34.1803625312681,35.4134069553251,36.646451379382,37.8794958034389,39.1125402274959,40.3455846515528,41.5786290756098,42.8116734996667,44.0447179237236,45.2777623477806,46.5108067718375,47.7438511958945,48.9768956199514,50.2099400440083,51.4429844680653],[16.1955701374006,17.4286145614576,18.6616589855145,19.8947034095714,21.1277478336284,22.3607922576853,23.5938366817422,24.8268811057992,26.0599255298561,27.2929699539131,28.52601437797,29.7590588020269,30.9921032260839,32.2251476501408,33.4581920741978,34.6912364982547,35.9242809223116,37.1573253463686,38.3903697704255,39.6234141944825,40.8564586185394,42.0895030425963,43.3225474666533,44.5555918907102,45.7886363147672,47.0216807388241,48.254725162881,49.487769586938,50.7208140109949,51.9538584350518],[16.7064441043872,17.9394885284441,19.1725329525011,20.405577376558,21.6386218006149,22.8716662246719,24.1047106487288,25.3377550727858,26.5707994968427,27.8038439208996,29.0368883449566,30.2699327690135,31.5029771930705,32.7360216171274,33.9690660411843,35.2021104652413,36.4351548892982,37.6681993133551,38.9012437374121,40.134288161469,41.367332585526,42.6003770095829,43.8334214336398,45.0664658576968,46.2995102817537,47.5325547058107,48.7655991298676,49.9986435539245,51.2316879779815,52.4647324020384],[17.2173180713738,18.4503624954307,19.6834069194876,20.9164513435446,22.1494957676015,23.3825401916584,24.6155846157154,25.8486290397723,27.0816734638293,28.3147178878862,29.5477623119431,30.7808067360001,32.013851160057,33.246895584114,34.4799400081709,35.7129844322278,36.9460288562848,38.1790732803417,39.4121177043987,40.6451621284556,41.8782065525125,43.1112509765695,44.3442954006264,45.5773398246834,46.8103842487403,48.0434286727972,49.2764730968542,50.5095175209111,51.7425619449681,52.975606369025],[17.7281920383603,18.9612364624173,20.1942808864742,21.4273253105312,22.6603697345881,23.893414158645,25.126458582702,26.3595030067589,27.5925474308158,28.8255918548728,30.0586362789297,31.2916807029867,32.5247251270436,33.7577695511005,34.9908139751575,36.2238583992144,37.4569028232714,38.6899472473283,39.9229916713852,41.1560360954422,42.3890805194991,43.6221249435561,44.855169367613,46.0882137916699,47.3212582157269,48.5543026397838,49.7873470638408,51.0203914878977,52.2534359119546,53.4864803360116],[18.2390660053469,19.4721104294038,20.7051548534608,21.9381992775177,23.1712437015747,24.4042881256316,25.6373325496885,26.8703769737455,28.1034213978024,29.3364658218594,30.5695102459163,31.8025546699732,33.0355990940302,34.2686435180871,35.5016879421441,36.734732366201,37.9677767902579,39.2008212143149,40.4338656383718,41.6669100624287,42.8999544864857,44.1329989105426,45.3660433345996,46.5990877586565,47.8321321827135,49.0651766067704,50.2982210308273,51.5312654548843,52.7643098789412,53.9973543029981],[18.7499399723335,19.9829843963904,21.2160288204474,22.4490732445043,23.6821176685612,24.9151620926182,26.1482065166751,27.3812509407321,28.614295364789,29.8473397888459,31.0803842129029,32.3134286369598,33.5464730610168,34.7795174850737,36.0125619091306,37.2456063331876,38.4786507572445,39.7116951813015,40.9447396053584,42.1777840294153,43.4108284534723,44.6438728775292,45.8769173015861,47.1099617256431,48.3430061497,49.576050573757,50.8090949978139,52.0421394218708,53.2751838459278,54.5082282699847],[19.2608139393201,20.493858363377,21.7269027874339,22.9599472114909,24.1929916355478,25.4260360596048,26.6590804836617,27.8921249077186,29.1251693317756,30.3582137558325,31.5912581798895,32.8243026039464,34.0573470280033,35.2903914520603,36.5234358761172,37.7564803001741,38.9895247242311,40.222569148288,41.455613572345,42.6886579964019,43.9217024204588,45.1547468445158,46.3877912685727,47.6208356926297,48.8538801166866,50.0869245407435,51.3199689648005,52.5530133888574,53.7860578129144,55.0191022369713],[19.7716879063066,21.0047323303636,22.2377767544205,23.4708211784775,24.7038656025344,25.9369100265913,27.1699544506483,28.4029988747052,29.6360432987621,30.8690877228191,32.102132146876,33.335176570933,34.5682209949899,35.8012654190468,37.0343098431038,38.2673542671607,39.5003986912177,40.7334431152746,41.9664875393315,43.1995319633885,44.4325763874454,45.6656208115024,46.8986652355593,48.1317096596162,49.3647540836732,50.5977985077301,51.8308429317871,53.063887355844,54.2969317799009,55.5299762039579],[20.2825618732932,21.5156062973501,22.7486507214071,23.981695145464,25.214739569521,26.4477839935779,27.6808284176348,28.9138728416918,30.1469172657487,31.3799616898057,32.6130061138626,33.8460505379195,35.0790949619765,36.3121393860334,37.5451838100904,38.7782282341473,40.0112726582042,41.2443170822612,42.4773615063181,43.710405930375,44.943450354432,46.1764947784889,47.4095392025459,48.6425836266028,49.8756280506597,51.1086724747167,52.3417168987736,53.5747613228306,54.8078057468875,56.0408501709444],[20.7934358402798,22.0264802643367,23.2595246883937,24.4925691124506,25.7256135365075,26.9586579605645,28.1917023846214,29.4247468086784,30.6577912327353,31.8908356567922,33.1238800808492,34.3569245049061,35.589968928963,36.82301335302,38.0560577770769,39.2891022011339,40.5221466251908,41.7551910492477,42.9882354733047,44.2212798973616,45.4543243214186,46.6873687454755,47.9204131695324,49.1534575935894,50.3865020176463,51.6195464417033,52.8525908657602,54.0856352898171,55.3186797138741,56.551724137931],[21.3043098072664,22.5373542313233,23.7703986553802,25.0034430794372,26.2364875034941,27.469531927551,28.702576351608,29.9356207756649,31.1686651997219,32.4017096237788,33.6347540478357,34.8677984718927,36.1008428959496,37.3338873200066,38.5669317440635,39.7999761681204,41.0330205921774,42.2660650162343,43.4991094402913,44.7321538643482,45.9651982884051,47.1982427124621,48.431287136519,49.664331560576,50.8973759846329,52.1304204086898,53.3634648327468,54.5965092568037,55.8295536808606,57.0625981049176],[21.8151837742529,23.0482281983099,24.2812726223668,25.5143170464238,26.7473614704807,27.9804058945376,29.2134503185946,30.4464947426515,31.6795391667084,32.9125835907654,34.1456280148223,35.3786724388793,36.6117168629362,37.8447612869931,39.0778057110501,40.310850135107,41.543894559164,42.7769389832209,44.0099834072778,45.2430278313348,46.4760722553917,47.7091166794487,48.9421611035056,50.1752055275625,51.4082499516195,52.6412943756764,53.8743387997334,55.1073832237903,56.3404276478472,57.5734720719042],[22.3260577412395,23.5591021652964,24.7921465893534,26.0251910134103,27.2582354374673,28.4912798615242,29.7243242855811,30.9573687096381,32.190413133695,33.423457557752,34.6565019818089,35.8895464058658,37.1225908299228,38.3556352539797,39.5886796780367,40.8217241020936,42.0547685261505,43.2878129502075,44.5208573742644,45.7539017983213,46.9869462223783,48.2199906464352,49.4530350704922,50.6860794945491,51.919123918606,53.152168342663,54.3852127667199,55.6182571907769,56.8513016148338,58.0843460388907],[22.8369317082261,24.069976132283,25.30302055634,26.5360649803969,27.7691094044538,29.0021538285108,30.2351982525677,31.4682426766247,32.7012871006816,33.9343315247385,35.1673759487955,36.4004203728524,37.6334647969094,38.8665092209663,40.0995536450232,41.3325980690802,42.5656424931371,43.798686917194,45.031731341251,46.2647757653079,47.4978201893649,48.7308646134218,49.9639090374788,51.1969534615357,52.4299978855926,53.6630423096496,54.8960867337065,56.1291311577634,57.3621755818204,58.5952200058773],[23.3478056752127,24.5808500992696,25.8138945233265,27.0469389473835,28.2799833714404,29.5130277954974,30.7460722195543,31.9791166436112,33.2121610676682,34.4452054917251,35.678249915782,36.911294339839,38.1443387638959,39.3773831879529,40.6104276120098,41.8434720360667,43.0765164601237,44.3095608841806,45.5426053082376,46.7756497322945,48.0086941563514,49.2417385804084,50.4747830044653,51.7078274285223,52.9408718525792,54.1739162766361,55.4069607006931,56.64000512475,57.873049548807,59.1060939728639],[23.8586796421992,25.0917240662562,26.3247684903131,27.5578129143701,28.790857338427,30.0239017624839,31.2569461865409,32.4899906105978,33.7230350346547,34.9560794587117,36.1891238827686,37.4221683068256,38.6552127308825,39.8882571549394,41.1213015789964,42.3543460030533,43.5873904271103,44.8204348511672,46.0534792752241,47.2865236992811,48.519568123338,49.752612547395,50.9856569714519,52.2187013955088,53.4517458195658,54.6847902436227,55.9178346676796,57.1508790917366,58.3839235157935,59.6169679398505],[24.3695536091858,25.6025980332427,26.8356424572997,28.0686868813566,29.3017313054136,30.5347757294705,31.7678201535274,33.0008645775844,34.2339090016413,35.4669534256983,36.6999978497552,37.9330422738121,39.1660866978691,40.399131121926,41.6321755459829,42.8652199700399,44.0982643940968,45.3313088181538,46.5643532422107,47.7973976662676,49.0304420903246,50.2634865143815,51.4965309384385,52.7295753624954,53.9626197865523,55.1956642106093,56.4287086346662,57.6617530587232,58.8947974827801,60.127841906837],[24.8804275761724,26.1134720002293,27.3465164242863,28.5795608483432,29.8126052724001,31.0456496964571,32.278694120514,33.511738544571,34.7447829686279,35.9778273926848,37.2108718167418,38.4439162407987,39.6769606648557,40.9100050889126,42.1430495129695,43.3760939370265,44.6091383610834,45.8421827851403,47.0752272091973,48.3082716332542,49.5413160573112,50.7743604813681,52.007404905425,53.240449329482,54.4734937535389,55.7065381775959,56.9395826016528,58.1726270257097,59.4056714497667,60.6387158738236],[25.391301543159,26.6243459672159,27.8573903912728,29.0904348153298,30.3234792393867,31.5565236634437,32.7895680875006,34.0226125115575,35.2556569356145,36.4887013596714,37.7217457837284,38.9547902077853,40.1878346318422,41.4208790558992,42.6539234799561,43.886967904013,45.12001232807,46.3530567521269,47.5861011761839,48.8191456002408,50.0521900242977,51.2852344483547,52.5182788724116,53.7513232964686,54.9843677205255,56.2174121445824,57.4504565686394,58.6835009926963,59.9165454167533,61.1495898408102],[25.9021755101455,27.1352199342025,28.3682643582594,29.6013087823164,30.8343532063733,32.0673976304302,33.3004420544872,34.5334864785441,35.766530902601,36.999575326658,38.2326197507149,39.4656641747719,40.6987085988288,41.9317530228857,43.1647974469427,44.3978418709996,45.6308862950566,46.8639307191135,48.0969751431704,49.3300195672274,50.5630639912843,51.7961084153413,53.0291528393982,54.2621972634551,55.4952416875121,56.728286111569,57.961330535626,59.1943749596829,60.4274193837398,61.6604638077968],[26.4130494771321,27.646093901189,28.879138325246,30.1121827493029,31.3452271733599,32.5782715974168,33.8113160214737,35.0443604455307,36.2774048695876,37.5104492936446,38.7434937177015,39.9765381417584,41.2095825658154,42.4426269898723,43.6756714139293,44.9087158379862,46.1417602620431,47.3748046861001,48.607849110157,49.8408935342139,51.0739379582709,52.3069823823278,53.5400268063848,54.7730712304417,56.0061156544987,57.2391600785556,58.4722045026125,59.7052489266695,60.9382933507264,62.1713377747833],[26.9239234441187,28.1569678681756,29.3900122922326,30.6230567162895,31.8561011403464,33.0891455644034,34.3221899884603,35.5552344125173,36.7882788365742,38.0213232606311,39.2543676846881,40.487412108745,41.7204565328019,42.9535009568589,44.1865453809158,45.4195898049728,46.6526342290297,47.8856786530866,49.1187230771436,50.3517675012005,51.5848119252575,52.8178563493144,54.0509007733713,55.2839451974283,56.5169896214852,57.7500340455422,58.9830784695991,60.216122893656,61.449167317713,62.6822117417699],[27.4347974111053,28.6678418351622,29.9008862592191,31.1339306832761,32.366975107333,33.6000195313899,34.8330639554469,36.0661083795038,37.2991528035608,38.5321972276177,39.7652416516746,40.9982860757316,42.2313304997885,43.4643749238455,44.6974193479024,45.9304637719593,47.1635081960163,48.3965526200732,49.6295970441302,50.8626414681871,52.095685892244,53.328730316301,54.5617747403579,55.7948191644149,57.0278635884718,58.2609080125287,59.4939524365857,60.7269968606426,61.9600412846995,63.1930857087565],[27.9456713780918,29.1787158021488,30.4117602262057,31.6448046502626,32.8778490743196,34.1108934983765,35.3439379224335,36.5769823464904,37.8100267705473,39.0430711946043,40.2761156186612,41.5091600427182,42.7422044667751,43.975248890832,45.208293314889,46.4413377389459,47.6743821630028,48.9074265870598,50.1404710111167,51.3735154351737,52.6065598592306,53.8396042832875,55.0726487073445,56.3056931314014,57.5387375554584,58.7717819795153,60.0048264035722,61.2378708276292,62.4709152516861,63.7039596757431]],\"showlegend\":false,\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"surface\",\"showscale\":false,\"colorscale\":[[0,1],[\"tan\",\"tan\"]],\"name\":\"Linear Model\",\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"xaxis\":{\"title\":\"food\"},\"yaxis\":{\"title\":\"decor\"},\"zaxis\":{\"title\":\"price\"}},\"hovermode\":\"closest\",\"showlegend\":false},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false,\"displayModeBar\":false},\"data\":[{\"x\":[19],\"y\":[15],\"z\":[33],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Amarone\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Anche Vivolo\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[18],\"y\":[17],\"z\":[33],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Andiamo\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[41],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Arno\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[20],\"y\":[19],\"z\":[44],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Artusi\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[17],\"y\":[15],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Baci\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[17],\"y\":[18],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Baraonda\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[16],\"y\":[16],\"z\":[44],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Barbaresco\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[20],\"y\":[23],\"z\":[52],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Barbetta\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[18],\"y\":[13],\"z\":[24],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Bardolino\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[18],\"y\":[15],\"z\":[32],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Basta Pasta\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[20],\"y\":[17],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Becco\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Bella Luna\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[22],\"y\":[21],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Bellini\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[21],\"y\":[17],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Bello\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[22],\"y\":[19],\"z\":[39],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Belluno\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[21],\"y\":[20],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Bice\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[21],\"y\":[13],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Biricchino\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[20],\"y\":[17],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Bond� Ristorante�\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[20],\"y\":[20],\"z\":[41],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Bottino\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[22],\"y\":[17],\"z\":[56],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Bravo Gianni\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[22],\"y\":[19],\"z\":[50],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Bruno Ristorante\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[23],\"y\":[19],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Cafe Trevi\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[18],\"y\":[17],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Caffe Cielo\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Caffe Grazie\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[24],\"y\":[21],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Campagna\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[24],\"y\":[20],\"z\":[53],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Campagnola\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[22],\"y\":[17],\"z\":[44],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Canaletto\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[19],\"y\":[15],\"z\":[29],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Cara Mia\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[19],\"y\":[13],\"z\":[30],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Carino Ristorante\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[33],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Casa Di Meglio\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[20],\"y\":[19],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Casa Mia\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[21],\"y\":[18],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Castellano\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[22],\"y\":[20],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Cellini\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[20],\"y\":[16],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Chianti\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[19],\"y\":[19],\"z\":[40],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Ciao Europa\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[21],\"y\":[17],\"z\":[44],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Cinque Terre\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[22],\"y\":[24],\"z\":[53],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Circo Osteria del\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[22],\"y\":[21],\"z\":[55],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Coco Pazzo\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[20],\"y\":[19],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Coco Pazzo Caf�\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[18],\"y\":[18],\"z\":[47],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Coco Pazzo Teatro\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[19],\"y\":[16],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Cucina Vivolo\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[22],\"y\":[19],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Da Antonio Ristorante\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[20],\"y\":[18],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Da Filippo\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[21],\"y\":[16],\"z\":[42],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Da Tommaso\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[24],\"y\":[19],\"z\":[54],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Da Umberto\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[22],\"y\":[18],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Daniella Ristorante\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[23],\"y\":[22],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"DeGrezia\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[19],\"y\":[15],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Divino Ristorante\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[22],\"y\":[18],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Due\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[20],\"y\":[20],\"z\":[40],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"East River Cafe\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[18],\"y\":[15],\"z\":[25],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Ecco-la\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[23],\"y\":[18],\"z\":[50],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Elio's\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[23],\"y\":[20],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Enoteca i Trulli\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[25],\"y\":[24],\"z\":[54],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Erminia\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[16],\"y\":[15],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Ernie's\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[25],\"y\":[22],\"z\":[62],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"FELIDIA\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Fino\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[21],\"y\":[19],\"z\":[41],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Firenze\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[23],\"y\":[20],\"z\":[48],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Follonico\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[19],\"y\":[18],\"z\":[39],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Fred's at Barneys NY\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[23],\"y\":[21],\"z\":[50],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Fresco by Scotto\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[22],\"y\":[19],\"z\":[50],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Gabriel's\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[24],\"y\":[10],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Gennaro\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[21],\"y\":[18],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Giambelli\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[20],\"y\":[14],\"z\":[41],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Gino\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[22],\"y\":[19],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Giovanni\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[21],\"y\":[18],\"z\":[48],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Giovanni Venticinque\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[21],\"y\":[18],\"z\":[50],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Girasole\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[35],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Grace's Trattoria\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[23],\"y\":[20],\"z\":[54],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Grifone\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[21],\"y\":[20],\"z\":[65],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Harry Cipriani\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[23],\"y\":[22],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"I Trulli\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[20],\"y\":[15],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Il Gatto & La Volpe\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[22],\"y\":[19],\"z\":[52],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Il Menestrello\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[23],\"y\":[20],\"z\":[55],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Il Monello\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[24],\"y\":[20],\"z\":[57],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Il Nido\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[24],\"y\":[21],\"z\":[57],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Il Postino\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[21],\"y\":[16],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Il Riccio\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[23],\"y\":[19],\"z\":[57],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Il Tinello\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[17],\"y\":[14],\"z\":[36],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Il Vagabondo\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[21],\"y\":[20],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Il Valentino\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[21],\"y\":[17],\"z\":[56],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Il Valletto Due Mila\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[19],\"y\":[18],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Joanna's\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[20],\"y\":[16],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"La Gioconda\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[21],\"y\":[15],\"z\":[42],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"La Grolla, Ristorante\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[19],\"y\":[16],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"La Rivista\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[18],\"y\":[9],\"z\":[19],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Lamarca\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[22],\"y\":[22],\"z\":[52],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Le Madri\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[22],\"y\":[16],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Le Zie\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[19],\"y\":[18],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Limoncello\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[21],\"y\":[15],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Luca\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[20],\"y\":[19],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Lumi\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Luna Blu\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[33],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Luna Piena\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[24],\"y\":[20],\"z\":[49],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Lusardi's\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[17],\"y\":[14],\"z\":[29],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Mangia e Bevi\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[21],\"y\":[19],\"z\":[47],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Marchi's\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[19],\"y\":[14],\"z\":[33],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Maruzzella\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[18],\"y\":[15],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Mediterraneo\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[19],\"y\":[15],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Mezzaluna\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[22],\"y\":[17],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"M�tisse\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[23],\"y\":[17],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Nanni's\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[54],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Nello\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[21],\"y\":[19],\"z\":[52],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Nicola Paone\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[22],\"y\":[18],\"z\":[50],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Nicola's\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[23],\"y\":[20],\"z\":[52],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Nino's\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[21],\"y\":[19],\"z\":[39],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Nocello\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[35],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Notaro\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[23],\"y\":[19],\"z\":[47],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Novit�\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[22],\"y\":[18],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Orso\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[20],\"y\":[18],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Osteria Laguna\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[20],\"y\":[17],\"z\":[40],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Osteria al Doge\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[22],\"y\":[25],\"z\":[63],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Palio\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[23],\"y\":[19],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Paola's\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Paper Moon Milano\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Pappardella\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[22],\"y\":[16],\"z\":[47],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Parma\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[20],\"y\":[18],\"z\":[34],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Pasticcio\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[20],\"y\":[16],\"z\":[42],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Patsy's\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[19],\"y\":[16],\"z\":[40],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Paul & Jimmy's\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[20],\"y\":[15],\"z\":[32],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Pietrasanta\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[20],\"y\":[17],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Pomodoro Rosso\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[24],\"y\":[22],\"z\":[60],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Primavera\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[23],\"y\":[17],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Primola\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[20],\"y\":[16],\"z\":[26],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Puccini\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[19],\"y\":[15],\"z\":[32],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Puttanesca\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[19],\"y\":[17],\"z\":[41],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Quattro Gatti\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[19],\"y\":[23],\"z\":[65],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Rainbow Grill\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[23],\"y\":[16],\"z\":[57],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Rao's\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[23],\"y\":[23],\"z\":[52],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Remi\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[36],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Ribollita\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[20],\"y\":[14],\"z\":[23],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Rino Trattoria\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[20],\"y\":[18],\"z\":[47],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Rossini's\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[23],\"y\":[19],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Rughetta\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[18],\"y\":[16],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Sal Anthony's\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[19],\"y\":[16],\"z\":[31],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Sambuca, Trattoria\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[23],\"y\":[22],\"z\":[65],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"San Domenico\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[22],\"y\":[20],\"z\":[51],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"San Giusto\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[24],\"y\":[21],\"z\":[58],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"San Pietro\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[21],\"y\":[19],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Scaletta\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[24],\"y\":[18],\"z\":[58],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Scalinatella\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[21],\"y\":[16],\"z\":[48],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Sette Mezzo\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[18],\"y\":[21],\"z\":[42],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Sette MoMA\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[23],\"y\":[16],\"z\":[36],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Sirabella's\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[23],\"y\":[19],\"z\":[54],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Sistina\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[19],\"y\":[18],\"z\":[39],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Spada\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[17],\"y\":[14],\"z\":[28],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Supreme Macaroni Co.\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[20],\"y\":[19],\"z\":[32],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Tello's Ristorante\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[21],\"y\":[17],\"z\":[41],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Teodora\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[20],\"y\":[18],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Tino's\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[19],\"y\":[14],\"z\":[30],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Tony's Di Napoli\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[19],\"y\":[21],\"z\":[47],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Torre di Pisa\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[21],\"y\":[19],\"z\":[37],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"Trattoria Alba\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[21],\"y\":[18],\"z\":[29],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Trattoria Del Sogno\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[17],\"y\":[16],\"z\":[38],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Trattoria Dopo Teatro\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[20],\"y\":[16],\"z\":[35],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Trattoria Rustica\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[20],\"y\":[16],\"z\":[33],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Triangolo\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[20],\"y\":[17],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"name\":\"Trionfo\",\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"line\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[19],\"y\":[20],\"z\":[40],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"name\":\"Tuscan Square\",\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"line\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[22],\"y\":[21],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Vago Ristorante\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[21],\"y\":[6],\"z\":[22],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"name\":\"Veronica\",\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[22],\"y\":[17],\"z\":[40],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"name\":\"Via Oreto\",\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[22],\"y\":[22],\"z\":[46],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"name\":\"ViceVersa\",\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[20],\"y\":[15],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"name\":\"Vico\",\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[22],\"y\":[18],\"z\":[45],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"name\":\"Villa Berulia\",\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[20],\"y\":[19],\"z\":[43],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"name\":\"Vivolo\",\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"line\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[17],\"y\":[14],\"z\":[29],\"showlegend\":false,\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"steelblue\",\"size\":5,\"opacity\":0.6,\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"name\":\"Zucchero e Pomodori\",\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"line\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"colorbar\":{\"title\":\"price\",\"ticklen\":2},\"colorscale\":[[0,\"tan\"],[1,\"tan\"]],\"showscale\":false,\"x\":[16,16.3103448275862,16.6206896551724,16.9310344827586,17.2413793103448,17.551724137931,17.8620689655172,18.1724137931034,18.4827586206897,18.7931034482759,19.1034482758621,19.4137931034483,19.7241379310345,20.0344827586207,20.3448275862069,20.6551724137931,20.9655172413793,21.2758620689655,21.5862068965517,21.8965517241379,22.2068965517241,22.5172413793103,22.8275862068966,23.1379310344828,23.448275862069,23.7586206896552,24.0689655172414,24.3793103448276,24.6896551724138,25],\"y\":[6,6.6551724137931,7.31034482758621,7.96551724137931,8.62068965517241,9.27586206896552,9.93103448275862,10.5862068965517,11.2413793103448,11.8965517241379,12.551724137931,13.2068965517241,13.8620689655172,14.5172413793103,15.1724137931034,15.8275862068966,16.4827586206897,17.1379310344828,17.7931034482759,18.448275862069,19.1034482758621,19.7586206896552,20.4137931034483,21.0689655172414,21.7241379310345,22.3793103448276,23.0344827586207,23.6896551724138,24.3448275862069,25],\"z\":[[13.1303263354812,14.3633707595381,15.596415183595,16.829459607652,18.0625040317089,19.2955484557659,20.5285928798228,21.7616373038797,22.9946817279367,24.2277261519936,25.4607705760505,26.6938150001075,27.9268594241644,29.1599038482214,30.3929482722783,31.6259926963352,32.8590371203922,34.0920815444491,35.3251259685061,36.558170392563,37.7912148166199,39.0242592406769,40.2573036647338,41.4903480887908,42.7233925128477,43.9564369369046,45.1894813609616,46.4225257850185,47.6555702090755,48.8886146331324],[13.6412003024677,14.8742447265247,16.1072891505816,17.3403335746386,18.5733779986955,19.8064224227524,21.0394668468094,22.2725112708663,23.5055556949232,24.7386001189802,25.9716445430371,27.2046889670941,28.437733391151,29.6707778152079,30.9038222392649,32.1368666633218,33.3699110873788,34.6029555114357,35.8359999354926,37.0690443595496,38.3020887836065,39.5351332076635,40.7681776317204,42.0012220557773,43.2342664798343,44.4673109038912,45.7003553279482,46.9333997520051,48.166444176062,49.399488600119],[14.1520742694543,15.3851186935113,16.6181631175682,17.8512075416251,19.0842519656821,20.317296389739,21.5503408137959,22.7833852378529,24.0164296619098,25.2494740859668,26.4825185100237,27.7155629340806,28.9486073581376,30.1816517821945,31.4146962062515,32.6477406303084,33.8807850543653,35.1138294784223,36.3468739024792,37.5799183265361,38.8129627505931,40.04600717465,41.279051598707,42.5120960227639,43.7451404468209,44.9781848708778,46.2112292949347,47.4442737189917,48.6773181430486,49.9103625671055],[14.6629482364409,15.8959926604978,17.1290370845548,18.3620815086117,19.5951259326686,20.8281703567256,22.0612147807825,23.2942592048395,24.5273036288964,25.7603480529533,26.9933924770103,28.2264369010672,29.4594813251242,30.6925257491811,31.925570173238,33.158614597295,34.3916590213519,35.6247034454088,36.8577478694658,38.0907922935227,39.3238367175797,40.5568811416366,41.7899255656936,43.0229699897505,44.2560144138074,45.4890588378644,46.7221032619213,47.9551476859782,49.1881921100352,50.4212365340921],[15.1738222034275,16.4068666274844,17.6399110515413,18.8729554755983,20.1059998996552,21.3390443237122,22.5720887477691,23.805133171826,25.038177595883,26.2712220199399,27.5042664439969,28.7373108680538,29.9703552921107,31.2033997161677,32.4364441402246,33.6694885642816,34.9025329883385,36.1355774123954,37.3686218364524,38.6016662605093,39.8347106845662,41.0677551086232,42.3007995326801,43.5338439567371,44.766888380794,45.9999328048509,47.2329772289079,48.4660216529648,49.6990660770218,50.9321105010787],[15.684696170414,16.917740594471,18.1507850185279,19.3838294425849,20.6168738666418,21.8499182906987,23.0829627147557,24.3160071388126,25.5490515628695,26.7820959869265,28.0151404109834,29.2481848350404,30.4812292590973,31.7142736831542,32.9473181072112,34.1803625312681,35.4134069553251,36.646451379382,37.8794958034389,39.1125402274959,40.3455846515528,41.5786290756098,42.8116734996667,44.0447179237236,45.2777623477806,46.5108067718375,47.7438511958945,48.9768956199514,50.2099400440083,51.4429844680653],[16.1955701374006,17.4286145614576,18.6616589855145,19.8947034095714,21.1277478336284,22.3607922576853,23.5938366817422,24.8268811057992,26.0599255298561,27.2929699539131,28.52601437797,29.7590588020269,30.9921032260839,32.2251476501408,33.4581920741978,34.6912364982547,35.9242809223116,37.1573253463686,38.3903697704255,39.6234141944825,40.8564586185394,42.0895030425963,43.3225474666533,44.5555918907102,45.7886363147672,47.0216807388241,48.254725162881,49.487769586938,50.7208140109949,51.9538584350518],[16.7064441043872,17.9394885284441,19.1725329525011,20.405577376558,21.6386218006149,22.8716662246719,24.1047106487288,25.3377550727858,26.5707994968427,27.8038439208996,29.0368883449566,30.2699327690135,31.5029771930705,32.7360216171274,33.9690660411843,35.2021104652413,36.4351548892982,37.6681993133551,38.9012437374121,40.134288161469,41.367332585526,42.6003770095829,43.8334214336398,45.0664658576968,46.2995102817537,47.5325547058107,48.7655991298676,49.9986435539245,51.2316879779815,52.4647324020384],[17.2173180713738,18.4503624954307,19.6834069194876,20.9164513435446,22.1494957676015,23.3825401916584,24.6155846157154,25.8486290397723,27.0816734638293,28.3147178878862,29.5477623119431,30.7808067360001,32.013851160057,33.246895584114,34.4799400081709,35.7129844322278,36.9460288562848,38.1790732803417,39.4121177043987,40.6451621284556,41.8782065525125,43.1112509765695,44.3442954006264,45.5773398246834,46.8103842487403,48.0434286727972,49.2764730968542,50.5095175209111,51.7425619449681,52.975606369025],[17.7281920383603,18.9612364624173,20.1942808864742,21.4273253105312,22.6603697345881,23.893414158645,25.126458582702,26.3595030067589,27.5925474308158,28.8255918548728,30.0586362789297,31.2916807029867,32.5247251270436,33.7577695511005,34.9908139751575,36.2238583992144,37.4569028232714,38.6899472473283,39.9229916713852,41.1560360954422,42.3890805194991,43.6221249435561,44.855169367613,46.0882137916699,47.3212582157269,48.5543026397838,49.7873470638408,51.0203914878977,52.2534359119546,53.4864803360116],[18.2390660053469,19.4721104294038,20.7051548534608,21.9381992775177,23.1712437015747,24.4042881256316,25.6373325496885,26.8703769737455,28.1034213978024,29.3364658218594,30.5695102459163,31.8025546699732,33.0355990940302,34.2686435180871,35.5016879421441,36.734732366201,37.9677767902579,39.2008212143149,40.4338656383718,41.6669100624287,42.8999544864857,44.1329989105426,45.3660433345996,46.5990877586565,47.8321321827135,49.0651766067704,50.2982210308273,51.5312654548843,52.7643098789412,53.9973543029981],[18.7499399723335,19.9829843963904,21.2160288204474,22.4490732445043,23.6821176685612,24.9151620926182,26.1482065166751,27.3812509407321,28.614295364789,29.8473397888459,31.0803842129029,32.3134286369598,33.5464730610168,34.7795174850737,36.0125619091306,37.2456063331876,38.4786507572445,39.7116951813015,40.9447396053584,42.1777840294153,43.4108284534723,44.6438728775292,45.8769173015861,47.1099617256431,48.3430061497,49.576050573757,50.8090949978139,52.0421394218708,53.2751838459278,54.5082282699847],[19.2608139393201,20.493858363377,21.7269027874339,22.9599472114909,24.1929916355478,25.4260360596048,26.6590804836617,27.8921249077186,29.1251693317756,30.3582137558325,31.5912581798895,32.8243026039464,34.0573470280033,35.2903914520603,36.5234358761172,37.7564803001741,38.9895247242311,40.222569148288,41.455613572345,42.6886579964019,43.9217024204588,45.1547468445158,46.3877912685727,47.6208356926297,48.8538801166866,50.0869245407435,51.3199689648005,52.5530133888574,53.7860578129144,55.0191022369713],[19.7716879063066,21.0047323303636,22.2377767544205,23.4708211784775,24.7038656025344,25.9369100265913,27.1699544506483,28.4029988747052,29.6360432987621,30.8690877228191,32.102132146876,33.335176570933,34.5682209949899,35.8012654190468,37.0343098431038,38.2673542671607,39.5003986912177,40.7334431152746,41.9664875393315,43.1995319633885,44.4325763874454,45.6656208115024,46.8986652355593,48.1317096596162,49.3647540836732,50.5977985077301,51.8308429317871,53.063887355844,54.2969317799009,55.5299762039579],[20.2825618732932,21.5156062973501,22.7486507214071,23.981695145464,25.214739569521,26.4477839935779,27.6808284176348,28.9138728416918,30.1469172657487,31.3799616898057,32.6130061138626,33.8460505379195,35.0790949619765,36.3121393860334,37.5451838100904,38.7782282341473,40.0112726582042,41.2443170822612,42.4773615063181,43.710405930375,44.943450354432,46.1764947784889,47.4095392025459,48.6425836266028,49.8756280506597,51.1086724747167,52.3417168987736,53.5747613228306,54.8078057468875,56.0408501709444],[20.7934358402798,22.0264802643367,23.2595246883937,24.4925691124506,25.7256135365075,26.9586579605645,28.1917023846214,29.4247468086784,30.6577912327353,31.8908356567922,33.1238800808492,34.3569245049061,35.589968928963,36.82301335302,38.0560577770769,39.2891022011339,40.5221466251908,41.7551910492477,42.9882354733047,44.2212798973616,45.4543243214186,46.6873687454755,47.9204131695324,49.1534575935894,50.3865020176463,51.6195464417033,52.8525908657602,54.0856352898171,55.3186797138741,56.551724137931],[21.3043098072664,22.5373542313233,23.7703986553802,25.0034430794372,26.2364875034941,27.469531927551,28.702576351608,29.9356207756649,31.1686651997219,32.4017096237788,33.6347540478357,34.8677984718927,36.1008428959496,37.3338873200066,38.5669317440635,39.7999761681204,41.0330205921774,42.2660650162343,43.4991094402913,44.7321538643482,45.9651982884051,47.1982427124621,48.431287136519,49.664331560576,50.8973759846329,52.1304204086898,53.3634648327468,54.5965092568037,55.8295536808606,57.0625981049176],[21.8151837742529,23.0482281983099,24.2812726223668,25.5143170464238,26.7473614704807,27.9804058945376,29.2134503185946,30.4464947426515,31.6795391667084,32.9125835907654,34.1456280148223,35.3786724388793,36.6117168629362,37.8447612869931,39.0778057110501,40.310850135107,41.543894559164,42.7769389832209,44.0099834072778,45.2430278313348,46.4760722553917,47.7091166794487,48.9421611035056,50.1752055275625,51.4082499516195,52.6412943756764,53.8743387997334,55.1073832237903,56.3404276478472,57.5734720719042],[22.3260577412395,23.5591021652964,24.7921465893534,26.0251910134103,27.2582354374673,28.4912798615242,29.7243242855811,30.9573687096381,32.190413133695,33.423457557752,34.6565019818089,35.8895464058658,37.1225908299228,38.3556352539797,39.5886796780367,40.8217241020936,42.0547685261505,43.2878129502075,44.5208573742644,45.7539017983213,46.9869462223783,48.2199906464352,49.4530350704922,50.6860794945491,51.919123918606,53.152168342663,54.3852127667199,55.6182571907769,56.8513016148338,58.0843460388907],[22.8369317082261,24.069976132283,25.30302055634,26.5360649803969,27.7691094044538,29.0021538285108,30.2351982525677,31.4682426766247,32.7012871006816,33.9343315247385,35.1673759487955,36.4004203728524,37.6334647969094,38.8665092209663,40.0995536450232,41.3325980690802,42.5656424931371,43.798686917194,45.031731341251,46.2647757653079,47.4978201893649,48.7308646134218,49.9639090374788,51.1969534615357,52.4299978855926,53.6630423096496,54.8960867337065,56.1291311577634,57.3621755818204,58.5952200058773],[23.3478056752127,24.5808500992696,25.8138945233265,27.0469389473835,28.2799833714404,29.5130277954974,30.7460722195543,31.9791166436112,33.2121610676682,34.4452054917251,35.678249915782,36.911294339839,38.1443387638959,39.3773831879529,40.6104276120098,41.8434720360667,43.0765164601237,44.3095608841806,45.5426053082376,46.7756497322945,48.0086941563514,49.2417385804084,50.4747830044653,51.7078274285223,52.9408718525792,54.1739162766361,55.4069607006931,56.64000512475,57.873049548807,59.1060939728639],[23.8586796421992,25.0917240662562,26.3247684903131,27.5578129143701,28.790857338427,30.0239017624839,31.2569461865409,32.4899906105978,33.7230350346547,34.9560794587117,36.1891238827686,37.4221683068256,38.6552127308825,39.8882571549394,41.1213015789964,42.3543460030533,43.5873904271103,44.8204348511672,46.0534792752241,47.2865236992811,48.519568123338,49.752612547395,50.9856569714519,52.2187013955088,53.4517458195658,54.6847902436227,55.9178346676796,57.1508790917366,58.3839235157935,59.6169679398505],[24.3695536091858,25.6025980332427,26.8356424572997,28.0686868813566,29.3017313054136,30.5347757294705,31.7678201535274,33.0008645775844,34.2339090016413,35.4669534256983,36.6999978497552,37.9330422738121,39.1660866978691,40.399131121926,41.6321755459829,42.8652199700399,44.0982643940968,45.3313088181538,46.5643532422107,47.7973976662676,49.0304420903246,50.2634865143815,51.4965309384385,52.7295753624954,53.9626197865523,55.1956642106093,56.4287086346662,57.6617530587232,58.8947974827801,60.127841906837],[24.8804275761724,26.1134720002293,27.3465164242863,28.5795608483432,29.8126052724001,31.0456496964571,32.278694120514,33.511738544571,34.7447829686279,35.9778273926848,37.2108718167418,38.4439162407987,39.6769606648557,40.9100050889126,42.1430495129695,43.3760939370265,44.6091383610834,45.8421827851403,47.0752272091973,48.3082716332542,49.5413160573112,50.7743604813681,52.007404905425,53.240449329482,54.4734937535389,55.7065381775959,56.9395826016528,58.1726270257097,59.4056714497667,60.6387158738236],[25.391301543159,26.6243459672159,27.8573903912728,29.0904348153298,30.3234792393867,31.5565236634437,32.7895680875006,34.0226125115575,35.2556569356145,36.4887013596714,37.7217457837284,38.9547902077853,40.1878346318422,41.4208790558992,42.6539234799561,43.886967904013,45.12001232807,46.3530567521269,47.5861011761839,48.8191456002408,50.0521900242977,51.2852344483547,52.5182788724116,53.7513232964686,54.9843677205255,56.2174121445824,57.4504565686394,58.6835009926963,59.9165454167533,61.1495898408102],[25.9021755101455,27.1352199342025,28.3682643582594,29.6013087823164,30.8343532063733,32.0673976304302,33.3004420544872,34.5334864785441,35.766530902601,36.999575326658,38.2326197507149,39.4656641747719,40.6987085988288,41.9317530228857,43.1647974469427,44.3978418709996,45.6308862950566,46.8639307191135,48.0969751431704,49.3300195672274,50.5630639912843,51.7961084153413,53.0291528393982,54.2621972634551,55.4952416875121,56.728286111569,57.961330535626,59.1943749596829,60.4274193837398,61.6604638077968],[26.4130494771321,27.646093901189,28.879138325246,30.1121827493029,31.3452271733599,32.5782715974168,33.8113160214737,35.0443604455307,36.2774048695876,37.5104492936446,38.7434937177015,39.9765381417584,41.2095825658154,42.4426269898723,43.6756714139293,44.9087158379862,46.1417602620431,47.3748046861001,48.607849110157,49.8408935342139,51.0739379582709,52.3069823823278,53.5400268063848,54.7730712304417,56.0061156544987,57.2391600785556,58.4722045026125,59.7052489266695,60.9382933507264,62.1713377747833],[26.9239234441187,28.1569678681756,29.3900122922326,30.6230567162895,31.8561011403464,33.0891455644034,34.3221899884603,35.5552344125173,36.7882788365742,38.0213232606311,39.2543676846881,40.487412108745,41.7204565328019,42.9535009568589,44.1865453809158,45.4195898049728,46.6526342290297,47.8856786530866,49.1187230771436,50.3517675012005,51.5848119252575,52.8178563493144,54.0509007733713,55.2839451974283,56.5169896214852,57.7500340455422,58.9830784695991,60.216122893656,61.449167317713,62.6822117417699],[27.4347974111053,28.6678418351622,29.9008862592191,31.1339306832761,32.366975107333,33.6000195313899,34.8330639554469,36.0661083795038,37.2991528035608,38.5321972276177,39.7652416516746,40.9982860757316,42.2313304997885,43.4643749238455,44.6974193479024,45.9304637719593,47.1635081960163,48.3965526200732,49.6295970441302,50.8626414681871,52.095685892244,53.328730316301,54.5617747403579,55.7948191644149,57.0278635884718,58.2609080125287,59.4939524365857,60.7269968606426,61.9600412846995,63.1930857087565],[27.9456713780918,29.1787158021488,30.4117602262057,31.6448046502626,32.8778490743196,34.1108934983765,35.3439379224335,36.5769823464904,37.8100267705473,39.0430711946043,40.2761156186612,41.5091600427182,42.7422044667751,43.975248890832,45.208293314889,46.4413377389459,47.6743821630028,48.9074265870598,50.1404710111167,51.3735154351737,52.6065598592306,53.8396042832875,55.0726487073445,56.3056931314014,57.5387375554584,58.7717819795153,60.0048264035722,61.2378708276292,62.4709152516861,63.7039596757431]],\"showlegend\":false,\"type\":\"surface\",\"name\":\"Linear Model\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nIf you inspect this plane carefully you're realize that the tilt of the plane is not quite the same in every dimension. The tilt in the decor dimension is just a little bit steeper than that in the food dimension, a geometric expression of the fact that the coefficient in front of decor, 1.88, is just a bit higher than the coefficient in front of food, 1.64.\n\n\n#### Interpreting coefficients\n\nWhen moving from simple linear regression, with one explanatory variable, to the multiple linear regression, with many, the interpretation of the coefficients becomes trickier but also more insightful.\n\nMathematically, the coefficient in front of food, 1.64, tells us the difference that we would expect to see in the response variable, price, when two Italian restaurants are separated by a food rating of one *and they have the same decor rating*. Said another way, controlling for decor, a one point increase in the food rating is associated with a \\$1.64 increase in the price. Similarly for decor: controlling for the quality of the food, a one-point increase in decor is associated with a \\$1.88 increase in the price.\n\nThis conditional interpretation of the coefficients extends to the first setting we looked at, when one variable is numerical and the other is a dummy. Here is that model:\n\n$$\\widehat{price} = -15.97 + 2.87 \\times food - 1.45 \\times geowest$$\n\nFor two restaurants both on the same side of Manhattan, a one point increase in food score is associated with a \\$2.87 increase in the price of a meal. Also, for two restaurants with the exact same quality of food, the restaurant on the west side is expected to be \\$1.45 cheaper than the restaurant on the east side. This is a useful bit of insight - it gives a sense of what the premium is of being on the eastside. \n\nIt is also visible in the geometry of the model. When we're looking at restaurants with the same food quality, we're looking at a vertical slice of the scatter plot. Here the vertical line gray line is indicating restaurants where the food quality gets a score of 18. The difference in expected price of meals on the east side and west side is the vertical distance between the red line and the blue line, which is exactly 1.45.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](notes_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n<!-- ## Simpson's Paradox -->\n\n## Summary\n\nWe began this unit on Summarizing Data with graphical and numerical summaries of just a single variable: histograms and bar charts, means and standard deviations. In the last set of notes we introduced our first bivariate numerical summaries: the correlation coefficient, and the linear model. In these notes, we introduced multiple linear regression, a method that can numerically describe the linear relationships between an unlimited number of variables. The types of variables that can be included in these models is similarly vast. Numerical variables can be included directly, generalizing the geometry of a line into a plane in higher dimension. Categorical variables can be included using the trick of dummy variables, logical variables that take a value of 1 where a particular condition is true. The interpretation of all of the coefficients that result from a multiple regression is challenging but rewarding: it allows us to answer questions about the relationship between two variables after controlling for the values of other variables.\n\nIf this felt like a deep dive into a multiple linear regression, don't worry. Linear models are one of the most commonly used statistical tools, so we'll be revisiting them throughout the course: investigating their use in making generalizations, causal claims, and predictions.\n\n\n",
    "supporting": [
      "notes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/htmlwidgets-1.6.1/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.1/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}