# Taxonomy of Data

#### Concept Acquisition

1. R is a calculator that can save objects; but with functions and objects that are far richer than a normal calculator
1. R scripts or Qmd files as final draft of code; the console as the sandbox
1. Functions generally have input, optional args, and output. Some operate by collapsing a vector into a scalar; others operate on each element of a vector separately.
1. Help files are a good way to learn how to use a function.
1. Data types are encoded in R’s classes.
1. The vector is a data structure used for storing values that share the same type (linked to the notion of a variable).
1. The data frame is a data structure that binds together vectors of the same length and is a direct implementation of the general notion of data frame.


#### Tool Acquisition

1. `+`, `-`, `*`, `/`, `^`
1. `<-`
1. `?`
1. `library()`
1. `c()`
1. `class()`
1. `sum()`
1. `log()`
1. `mean()`
1. `tibble()`
1. `factor()`


#### Concept Application

1. Carry out basic mathematical operations on vectors.
1. Create vectors of various types and use them to construct data frames.
1. Distinguish between different classes of vectors.
1. Form a factor vector and specify the order of its levels.

