---
title: "Summarizing Numerical Data"
date: "09/07/2022"
---

[PDF]{.btn .btn-primary} [Perusall]{.btn .btn-warning} [Reading Questions]{.btn .btn-success}

# Question 1

Which of the following plot types maintain all of the information found in the original data set?

(X) dot plot
( ) histogram
( ) violin plot
( ) box plot

# Question 2

If you wish to see *less* detail in your histogram and perform *more* aggregation, which of the following is the best course of action?

( ) switch to a dot plot
( ) switch to a bar chart
( ) instead of presenting the histogram, display the original data frame with the raw data
(X) increase the bin width of the histogram
( ) decrease the bin width of the histogram

# Question 3

Which word best describes a distribution with a long tail stretching out to the left?

(X) left skewed
( ) right skewed
( ) unimodal
( ) heteroskedastic

# Question 4

In which situation does the median do a better job than the mean at capturing the center of a distribution? Select the best answer.

( ) when the median is less than the mean
( ) when the median is greater than the mean
(X) when the variable under study is known to have a strongly skewed distribution
( ) when the mode doesn't exist



{{< include ../../assets/_links-to-materials.qmd >}}
