---
title: "Wrong by Design"
format: stat20handout-pdf
---

<!-- Revise these to be settings where a hypothesis test makes sense (where there is a source of randomness in the data collection.) -->

## Question 1

For each of the following sets of hypotheses, determine whether committing a Type I error or a Type II error has greater real-world consequences. Explain your decision.

### Part A

Imagine that the San Francisco Giants hold a book donation promotion for one of their games where every individual who brings a used book to the stadium is allowed free entry. 

$H_0$: The number of individuals who wish attend the game will be no more than the capacity of the stadium.

$H_A$: The number of individuals who wish to attend the game will exceed the capacity of the stadium.

\
\
\
\
\

### Part B

$H_0$: A new operating system is **no more effective** for Carbon Health to use on the computers at its clinics than the old operating system.

$H_A$: A new operating system is **more effective** for Carbon Health to use on the computers at its clinics than the old operating system.

\
\
\
\
\

### Part C

$H_0$: The rate of COVID-19 infection on campus has not changed since last month.

$H_A$: The rate of COVID-19 infection on campus has increased since last month.

\
\
\
\
\
\
\


{{< pagebreak >}}

## Question 2

A food safety inspector is called upon to investigate a restaurant with a few customer reports of poor sanitation practices. The food safety inspector uses a hypothesis testing framework to evaluate whether regulations are not being met. If he decides the restaurant is in gross violation, its license to serve food will be revoked.

### Part A
Write the hypotheses in words.

\
\

### Part B
What is a Type 1 Error in this context?

\
\

### Part C
What is a Type 2 Error in this context?

\
\

### Part D
Which error is more problematic for the restaurant owner? Why?

\
\

### Part E
Which error is more problematic for the diners? Why?

\
\

### Part F
As a diner, would you prefer that the food safety inspector requires strong evidence or very strong evidence of health concerns before revoking a restaurant’s license? Explain your reasoning.