---
title: 'PS 9: A Matter of Taste II'
subtitle: "Data Analysis"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval = FALSE, 
                      echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

Be sure to tag your group mates when you submit this to Gradescope!

1. List any changes that you made to your experimental protocol.

2. Create a data frame based on the data you collected and print it out into your pdf. You can print all rows your data frame using `print(my_df, n = nrow(my_df))`. Consult the notes "A Tool for Computing with Data" for a refresher of how to make a dataframe.

3. Create a visualization of the data you collected (not the null distribution) similar to the one you sketched in the handout. Does it look clearly in support of your claim or contrary to your claim or somewhere in between?

4. Conduct a hypothesis test to determine whether your data is consistent with the null hypothesis. Be sure to provide.

    a. The null and alternative hypotheses.
    b. The value of the observed test statistic.
    c. A visualization of the null distribution and observed test statistic with the p-value shaded in.
    d. The p-value and your conclusion (use $\alpha = .05$) regarding null hypothesis and original claim.