---
title: "Random Variables"
subtitle: "PS"
format: stat20handout-pdf
---

#### Question 1: Binomial, hypergeometric, or neither?

In the following examples, 

- define an appropriate random variable
-  decide whether it is binomial, hypergeometric, or neither. 
-  if it is binomial or hypergeometric, identify the parameters of the distribution
-  compute the probability (you may leave it as an expression)

\vspace{2mm}

(a) The probability that 3 out of 8 tosses of a fair coin will land heads.

\vspace{4cm}

(b) The probability of rolling at least two 3’s and two 4’s out of twelve rolls of a die.

\vspace{4cm}


(c) The chance that there are exactly three diamonds among the first ten cards dealt off the top of a shuffled deck (note that cards are dealt without replacement).

\vspace{4cm}

(d) The chance that you have to roll a six-sided die 8 times until you get a total of 2 sixes.

\pagebreak

#### Question 2: Picking answer choices at random on a MC test

A test consists of $20$ multiple-choice questions. Each question has $4$ answer choices, of which only one is correct and three are incorrect. You answer each question by picking one of the four options at random, so how you answer one question has no bearing on the others (they are independent). Let $X$ be the number of questions you answer correctly. What is the chance that you answer more than 2 questions correctly?

\vspace{2.5cm}

#### Question 3: Committees

A committee of two is to be selected from among the five teachers and ten students attending a meeting. Let $X$ be the number of teachers selected for the committee. Write down the probability mass function for $X$.

\vspace{4cm}


#### Question 5: Box models and random variables

For the boxes below, draw one ticket at random, and let $X$ be the value of the ticket that you draw. Write down the pmf, and draw the graph of the cdf of $X$.

(a) \fbox{\fbox{-2} \fbox{-1} \fbox{0} \fbox{2}} \hspace{2in} (b) \fbox{\fbox{0} \fbox{1} \fbox{1} \fbox{6}}


