---
title: "Problem Set 6"
subtitle: "Due Monday, November 21"
format: pdf
editor: visual
---

# Questions

## Question 1

In order to study gender bias in promotion decisions, researchers took 48 resumes and randomly assigned them to 48 bank managers who were asked whether they would promote this candidate or not. The resumes were identical except the name: 24 of them had names generally associated with women, 24 of them had names generally associated with men. The data from this study can be found in the `promote` data frame. Use this data to determine whether gender played a role in promotion decisions.

The `promote` dataset can be found in the `stat20data` library.

### part a

Write the null and alternative hypothesis.

### part b

Compute the observed test statistic.

### part c

Visualize the observed data using an appropriate plot.

### part d

Construct a plot featuring 9 subplots, each one featuring a visualization of a data set generated under the null hypothesis. Does your visualization of the observed data from the previous part look like it could be one of these plots?

### part e

Construct and save the null distribution of statistics.

### part f

Visualize the null distribution.

### part g

Compute the p-value.

### part h

Interpret the p-value. What does it say about the consistency between the null hypothesis and the observed data?

## Question 2

Instead of conducting a hypothesis test concerning the difference in these proportions from **Question 1**, form a confidence interval for your estimate (what had been your observed test statistic). Use the bootstrap to form a 95% confidence interval for this statistic. Does it contain 0? How is this related to the result from question 1?

## Question 3


## Question 4

From the *Communication* lecture - to be released on Friday.



