---
title: "Practice Problems"
subtitle: "Confidence Intervals"
format: pdf
---

<!-- Goal: Give students practice calculating confidence intervals and talking through their interpretation and what effects their width. -->

<!-- These practice problems can be done in class in pairs/trios or at home for students who aren't in class. They will become part of the next problem set. The slides introduce / practice several functions used here. -->

<!-- Suggesting timeline: -->

<!-- 1. Review functions in slides -->
<!-- 2. Motivate setting: what if we only had data on 100 flights? How confident could we be that we have good estimates of the population parameters. -->
<!-- 3. Make students work in at least pairs for the handout. Ask that they draw their confidence intervals for the mean on the front board. You'll want to pre-populate the axes carefully and probably have them draw their intervals vertically so that they will all fit. Draw one on the board to demonstrate. -->
<!-- 3. At the end of the class period, review answers. -->

<!-- Technical Notes -->

<!-- 1. In the notes, the SE is the true SE calculated from the population (sigma / sqrt(n) for the mean). Here, we have them just use the data, so they use s / sqrt(n)) -->

The goal of these practice problems is to experiment with the notion of a sampling distribution and confidence intervals. In any applied setting, you only have access to a sample of the data, but for these practice problems we'll work with a data set where we have access to the full population: the flights data set. Here your goal is to use a small sample from that population to estimate two population parameters: a mean and a standard deviation.


#### Question 1

Our goal is to estimate the population mean of the air time variable using a small sample of the flights data. Load the `flights` data from the `stat20data` package that you used in Lab 4.

```{r}
#| echo: true
#| message: false
library(tidyverse)
library(stat20data)
data(flights)
```

Then:

- Set a seed of your choosing
- Take a random sample of 100 flights from `flights`
- Plot the empirical distribution of air time


#### Question 2

Calculate the mean and SD of air time in your sample. Assuming the the sampling distribution is roughly normal, what is your 68% confidence interval? Calculate it using these sample statistics.

#### Question 3

Did your interval contain the population mean? This is a rare case where you can check by calculating the average air time of the entire `flights` data set. If you repeated process 100 times - taking many samples and computing many intervals - how many of the resulting intervals would you expect to contain the population mean?

#### Question 4

Select a second population parameter to estimate, but in this case choose a **proportion** instead of a mean. For example: the proportion of flights that departed ahead of schedule (don't use this example). Using the same sample of flights as before:

1. Mutate a new logical variable that is interesting to you (e.g. whether or not a flight departed ahead of schedule).
2. Visualize that variable with a ggplot.
3. Calculate a sample proportion from this variable (see lab 4 for examples of this).
4. Form a 68% confidence interval, adapting it for a proportion by using the appropriate modifications from the notes (in this case, use your sample proportion).



#### Question 5

Did your interval contain the population proportion? This is a rare case where you can check by calculating the actual proportion found in the entire `flights` data set. If you repeated process 100 times - taking many samples and computing many intervals - how many of the resulting intervals would you expect to contain the population proportion?

#### Question 6

For both of the settings above - estimating a population mean and a population proportion - what are *two* things that can be changed to decrease the width of the confidence intervals?


#### Question 7

In these practice problems we treated the `flights` data as the target population (and access frame) then took simple random samples of size 100. In reality, the entire `flights` data set was the sample of data that we investigated in Lab 4.

Give an example of a larger target population to which you would be comfortable generalizing from the full `flights` data set. Provide another example of one to which you would *not* be comfortable generalizing. It may be helpful to sketch scope diagrams.
