---
title: "Understanding the World through Data"
date: "08/24/2022"
---

[PDF]{.btn .btn-primary} [Perusall]{.btn .btn-warning} [Reading Questions]{.btn .btn-success}

# Question 1

Which of the following best describes the distinction between R and RStudio?

( ) They're synonyms for the same thing.
(X) R is the language; RStudio is the tool we'll use to write and run R code.
( ) RStudio is the newer edition of the R language.
( ) R is a language of statistical computing; RStudio runs Excel.

# Question 2

How do you save the output of an R command into your Environment?

( ) Wrap the command in parentheses `()`.
( ) Wrap the commend in curly braces `{}`.
(X) Use the assignment arrow and provide a name for the output.
( ) Drag and drop the command into your environment.


## Question 3

The atomic building block of the R language is the ...

(X) vector
( ) variable
( ) numeric
( ) factor
( ) data frame


## Question 4

What type of vector can be used to best represent ordinal and nominal categorical variables?

( ) the variable
( ) numeric
( ) continuous
( ) discrete
(X) factor
