---
title: "People's Park"
subtitle: "Lab"
format: stat20handout-pdf
---

In answering the following questions, it will be helpful to consult the documents linked on the Lab 5 page on the course website.

#### Question 1

What was the goal(s) of the Chancellor's office in commissioning this survey?

\
\

#### Question 2

What is the population from which the Chancellor's office has drawn their sample? What is $N$?

\
\

#### Question 3

Describe two population parameters that the Chancellor's office is trying to estimate using the survey data.

\
\
\
\

#### Question 4

What was initial sample size of students selected to take the survey? What was the final sample size that actually did? What was the response rate?

\
\
\

#### Question 5

Identify possible sources of bias and whether they are selection, measurement, or nonresponse bias. How do you expect this will effect the estimate of the parameter?

\
\
\
\
\
\
\
\
\

{{< pagebreak >}}

#### Question 6

Identify possible sources of variation and whether they are sampling or measurement variability. How do you expect this will effect the estimate of the parameter?

\
\
\
\
\

#### Question 7

Consider the type of data collected in question 8 of the survey, which is measured using the Likert Scale. Review the Wikipedia article on the Likert Scale (particularly the Scoring and Analysis section) to determine: do you find it more useful to think of is variable as numerical discrete or categorical ordinal? What is your reasoning?

\
\
\
\
\
\
\
\

#### Question 8

Sketch a data frame of what the first 5 rows of the data frame might look like that contains the responses from the first 5 students. Include columns showing what the data might look like that comes out of questions 1, 7, and 8. Note that in the data set, the data values are all translated from words into numbers. Speculate as to how this translation is done.

\
\
\
\
\
\
\
\
\
\
\
\
\
\

{{< pagebreak >}}

#### Question 9

Sketch a plot of what the data might look like that is generated by each of the following survey questions. Note that this should be done without looking at the actual data frame.

A. Q. 9  
B. Q. 10  
C. Q. 18 and 21 (showing the change from before and after the information in one plot)

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\

#### Question 10

Select one parameter that you identified in Question 3 and and sketch what you think the sampling distribution of the statistic might look like given what you know about the data collection process. Be sure to label the axes. Add a vertical line on the sampling distribution that hits the x-axis where you expect the population parameter to be.
