---
title: "Baseball"
subtitle: "Lab"
format: stat20handout-typst
---

One source of data for this lab is the public `Lahman` database which contains a number of data sets with different units of observation. Below are the first few rows and some of the columns for two of these data sets: `Teams` and `Batting`. They contain data going back to 1871. Use these excerpts to help you answer the following questions.

```{r}
#| echo: false
#| warning: false
library(tidyverse)
library(Lahman)
library(infer)
set.seed(5)
knitr::kable(head(Teams %>% 
                    slice_sample(n = 6, replace = FALSE) %>%
                    select(yearID, teamID, franchID, G, W, L, R, RA, name) %>%
                    arrange(desc(yearID))
                  ))

knitr::kable(head(Batting %>% 
                    slice_sample(n = 6, replace = FALSE) %>%
                    select(playerID, yearID, teamID, G, AB, R, H, BB, SO) %>%
                    arrange(desc(yearID))
                  ))
```

1. What is the unit of observation for the Teams data set? What about for the Batting data set?

\
\
\

2. Write out two questions about baseball that could answered purely through *summaries* of these data sets (numerical summaries or plots).


\
\
\
\
\

3. Write out *predictive* questions (two classification and two regression) that you could answer about baseball using the data sets above. Identify a response variable for each.

{{< pagebreak >}}

4. What is a question that we would need more granular (measured on a finer/more specific part of the game) data than the `Teams` and `Batting` data sets provide to answer?

\
\
\
\

5. Roughly since 1962 MLB Teams have played 162 games in a season. What do you think the distribution of wins (`W`) looks like? Sketch a plot of what you think the *entire* wins column looks like, adding axis tick marks with plausible values, and describe the shape in words.

\
\
\
\
\
\
\
\
\
\
\
\
\
\

6. What do you think the relationship between wins (`W`) and runs (`R`) looks like? Sketch a plot, adding axis tick marks with plausible values, and describe the shape in words.


\
\
\
\
\
\
\
\
\
\
\
\
\
\
\

7. Some people believe analytics is ruining baseball because Teams are more cautious which makes the games less entertaining. Do you agree or disagree? Why? Answer in two or more sentences. 
 
\
\
\
\
\
\
\
