{
  "hash": "760cf80943c6a4257a246725d9046014",
  "result": {
    "markdown": "---\ntitle: \"Case Study: Pricing Homes\"\nformat:\n  revealjs:\n    author: \"STAT 20: Introduction to Probability and Statistics\"\n    height: 900\n    width: 1600\n    theme: ../../assets/slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: c\n    incremental: false\n    center: false\n    menu: false\n    highlight-style: github\n    progress: false\n    code-overflow: wrap\n    title-slide-attributes:\n      data-background-image: ../../assets/stat20-hex-bg.png\n      data-background-size: contain\n---\n\n\n## Agenda\n\n- Concept Questions\n- Practice: Pricing Houses\n- Break\n- Lab: Baseball\n\n# Concept Questions\n\n##\n\n:::{.poll}\nConsider two houses for sale, both 1,100 sqft, 2 bedroom, 1 bathroom, with a small garage, but one is in Santa Monica and the other is in Westwood. Which is true of the predicted sale prices of these two homes?\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_price ~ log_sqft + city, data = LA)\n\nCoefficients:\n     (Intercept)          log_sqft    cityLong Beach  citySanta Monica  \n         5.46554           1.15119          -0.89345          -0.09301  \n    cityWestwood  \n        -0.45846  \n```\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_9fa2dcee\" data-update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">01</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n:::\n:::\n\n\n\n:::{.notes}\nThis is a review question to assess if students can use model output to understand predictions. One way studnets may solve this is by plugging the x variables in to the corresponding formula and comparing the two predicted values. A student with stronger understanding will just compare the coefficients in front of cityWestwood and citySantaMonica. They both modify the reference level, which is Beverly Hills: SM is .1 log dollars less than the prediction for Beverly Hills and WW is .47 log dollars less than the prediction for Berkeley hills.\n\nThis is a good place to remind students that if they have transformed the respond variable prior to fitting their model, they will need to back-transform the predictions.\n:::\n\n## A simple model for price  \n\n\\\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4 <- lm(log_price ~ bed, data = LA)\n```\n:::\n\n\n\\\n\n::: poll\nWhat do you expect the *sign* of the coefficient for `bed` to be?\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_179b027c\" data-update-every=\"1\" tabindex=\"0\" style=\"top:0;right:0;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">01</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n:::\n:::\n\n\n:::{.notes}\nThere is no trick question here. It's asking students to rely on their common sense to know that houses with more bedrooms tend to be more expensive, therefore the sign of the coefficient should be positive.\n:::\n\n\n## A simple model for price  \n\n\\\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4 <- lm(log_price ~ bed, data = LA)\n```\n:::\n\n\n\\\n\n::: poll\nWhat do you expect the *sign* of the coefficient for `bed` to be?\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)   11.8      0.0436     271.  0        \n2 bed            0.532    0.0142      37.3 9.77e-220\n```\n:::\n:::\n\n\n\n## A less simple model for price  \n\n\\\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm5 <- lm(log_price ~ bed + log_sqft, data = LA)\n```\n:::\n\n\n\\\n\n::: poll\nWhat do you expect the *sign* of the coefficient for `bed` and `log_sqft` to be?\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_84374931\" data-update-every=\"1\" tabindex=\"0\" style=\"top:0;right:0;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">01</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n:::\n:::\n\n\n:::{.notes}\nThis is a tricky question for most students because they expect that since bed and logsqft both have positive relationships with the response in a simple linear regression model, that they should still have a positive relationship in the multivariate setting. That's not the case.\n\nThe best explanation involves asking the students a concrete question: \"Imagine two houses in Long Beach next door to one another. Both are 1,500 sqrt, have two bathrooms, and a single garage. One of them, however, has three bedrooms and the other has four bedrooms. Which home would you expect to be more expensive and why?\".\n\nStudents will generally realize that if you fix the square footage, the house with 4 bedrooms will have to divide the 1500 sqft into 4 very tiny bedrooms. The 3 bedroom house, by contrast, will have larger rooms and more generous living area, characteristics that tend to be prized more than an additional bedroom.\n\nThe plots that follow this question illustrate the effect by conditioning on one of the variables by faceting and looking at the association between the other variable and the response. The final plot does the operative comparison: if we discretize the logsqft, we can see that the association in the facets looks either flat or negative.\n:::\n\n## A less simple model for price  \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm5 <- lm(log(price) ~ bed + log_sqft, data = LA)\n```\n:::\n\n\n<br>\n\n::: poll\nWhat do you expect the *sign* of the coefficient for `bed` and `log_sqft` to be?\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)    1.47     0.218       6.73 2.28e- 11\n2 bed           -0.123    0.0164     -7.46 1.46e- 13\n3 log_sqft       1.66     0.0346     47.8  2.60e-310\n```\n:::\n:::\n\n\n\n## {}\nWhat is the relationship between `bed` and `log_price`?\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n## {}\n\nWhat is the relationship between `log_sqft` and `log_price`?\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n## {}\n\nWhat is the relationship between `log_sqft` and `log_price`, controlling for `bed`?\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n## {}\n\nWhat is the relationship between `bed` and `log_price`, controlling for `log_sqft`?\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n## Simpson's Paradox\n\nSimpson's paradox, which also goes by several other names, is a phenomenon in probability and statistics in which a trend appears in several groups of data but disappears or reverses when the groups are combined.\n\n![](images/simpsons.png){fig-align=center}\n\n[Source: Wikipedia]{.footer}\n\n\n# What is a *model*?\n\n. . .\n\n[A useful simplification of reality.]{.bigadage}\n\n. . .\n\n[A prediction machine.]{.bigadage}\n\n. . .\n\n[A specific answer to a specific question.]{.bigadage}\n\n\n## Model Interpretation\n\n**Question 1**\nWhat is the relationship between the number of bedrooms in a house and its price?\n\n. . .\n\n$$ \\widehat{\\textrm{log(price)}} = 11.8 + .53 \\textrm{bed}$$\n\n. . .\n\n**Question 2**\nAfter controlling for the size of a house, what is the relationship between the number of bedrooms in a house and its price?\n\n$$ \\widehat{\\textrm{log(price)}} = 11.8 + -0.12 \\textrm{bed} + 1.66 \\textrm{log(sqft)}$$\n\n# Practice: Pricing Houses\n\n## Practice: Pricing Houses\n\n\\\n\\\n\\\n\\\n\n:::{style=\"font-size: 1.3em; text-align: center\"}\nFocus on questions 1 and 2.\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_8d16ac07\" data-update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">08</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n:::\n:::\n\n\n## Practice: Pricing Houses\n\n\\\n\\\n\\\n\\\n\n:::{style=\"font-size: 1.3em; text-align: center\"}\nFocus on questions 3 - 5.\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_42909adb\" data-update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">10</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n:::\n:::\n\n\n## {background-image=\"images/zestimate1.png\"}\n\n:::{.notes}\nAs a follow up to Question 5 on the handout, zillow offers the zestimate prediction service to determine the value of a home based.\n\nThe final slide is the information that they provide about how their predictions work. They use a deep learning model framework, a more flexible extension of a linear model.\n:::\n\n## {background-image=\"images/zestimate2.png\"}\n\n## {background-image=\"images/zestimate3.png\" background-size=contain}\n\n# Lab 5: Baseball\n\n\n:::{.notes}\nIt's a good idea to read up a bit on the history and practice of sabermetrics before facilitating this lab. Some resources:\n\n- https://en.wikipedia.org/wiki/Sabermetrics\n- Moneyball the book: https://en.wikipedia.org/wiki/Moneyball\n- Moneyball the movie: https://en.wikipedia.org/wiki/Moneyball_(film)\n- Data sets used by sabermetricians: https://sabr.org/sabermetrics/data\n:::\n\n## Baseball Rules\n\n![](images/baseball_rules.png){fig-align=center width=600}\n\n:::{.notes}\nKey terms to define here are Runs (R) and Wins (W).\nHere's a helpful glossary from MLB: https://www.mlb.com/glossary\n:::\n\n## Baseball Rules\n\n![](images/baseball_diamond.png){fig-align=center width=600}\n\n\n## Sabermetrics\n\nCoined by Bill James in 1980, sabermetrics is\n\n> “the search for objective knowledge about baseball.”\n\n\n## History of Sabermetrics\n\n- Henry Chadwick, a NY sportswriter, developed the box score in 1958\n- \"Percentage Baseball\" by Earnshaw Cook in 1964\n- The Bill James Baseball Abstract, annual book beginning in 1977\n- [Moneyball](https://www.youtube.com/watch?v=Tzin1DgexlE)\n<!-- - [Moneyball](https://www.youtube.com/watch?v=pWgyy_rlmag) Alternative (crass) -->\n\n![](images/box_score.jpeg){fig-align=center width=600}\n\n\n\n",
    "supporting": [
      "slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/countdown-0.4.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/countdown-0.4.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}