---
format:
  pdf:
    include-in-header:
      - preamble.tex
      - fancyhdr.tex
    fontsize: 10pt
    margin-top: .8in
    margin-bottom: .5in
---

\thispagestyle{empty}

\begin{center}
\textsc{Stat 20: Lab 2.1 Class Survey} \\
\noindent\rule{12cm}{0.4pt}
\end{center}

1. What is the unit of observation in the survey of students in Stat 20?

\
\

2. Where in the Taxonomy of Data are the variables that correspond to each of the following survey questions (i.e., what is their type)?  
   - Question 7: What is your favorite thing about Cal?
   
   - Question 15: Where would you rather be?
   
   - Question 22: What is the chance that a fire alarm goes off in one of the dorms this week? 

\

3. What values would you expect `major` to take? Do you anticipate any challenges when analyzing this data?

\
\

Questions 4 - 7 can be answered using data visualization. To lay the groundwork for answering these questions using the survey data set, plan out your plots and set your expectations for what the data might look like. Please:

- sketch (with paper and pencil) a plot that captures the distribution or relationship between the variables,
- label the axis and add axis tick marks with plausible values,
- depict a shape that reflects your expectation of the phenomena,
- write out the *aesthetic mappings* (the variables in use and which visual cues / aesthetic each one is mapped to) and
- write out the *geometry* utilized by your plot.
  
4. Do students prefer to spend time at the beach or in the mountains?

{{< pagebreak >}}

5. How much coding experience do students have?

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\

6. What are students' perceptions of the chance that there is a new COVID variant that disrupts instruction in Spring 2023?

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\

7. What is the relationship between students' optimism for cryptocurrency and their skepticism of the effect of technology on interpersonal relationships?