---
title: "Covariate Balance and Natural Experiments"
subtitle: "investigating random treatment assignment"
format:
  html:
    code-fold: true
    code-link: true
    code-summary: "."
  pdf: default
execute: 
  warning: false
  message: false
---

<!-- Lead out with running example: are you reading these notes as a website or are you reading them as a pdf on a tablet? Do you think your choice in this regard will affect your understanding of the material and the course -->

[C]{.dropcap}ausation has a tricky relationship with data. We can't observe the precise counterfactual that would allow us to identify an individual cause. Instead, statisticians use a host of methods to find a good approximation of the counterfactual. In the last set of notes, randomized experimentation was presented as a method
for approximating group-level counterfactuals.  Randomized experimentation is a 
powerful idea but doesn't always work perfectly in practice.  In this set of notes, we will explore a tool called covariate balance which allows us to check how well
randomized assignment is working.  It will also help us evaluate causal claims 
in cases where researchers were not able to perform an experiment.

## Job training

[clickbait thing about getting a job, e.g. reference to movie or offspring song
or American Psycho meme]

Unemployment is a complex social problem.  It is not always easy for unemployed individuals
to ``just get a job."  For example, employers may be wary of hiring someone without
a recent work history, and job-seekers without advanced training may be offered
only such low-paid, high-effort work that they prefer to
sit out the labor market entirely.  

One strategy governments and nonprofit organization have contemplated for getting
people into the labor market is job training programs.  The idea is to give public
assistance to
people who might otherwise struggle to get quality employment while they engage
in short-term work experiences that also give them employable skills (e.g. construction, painting
office work, or healthcare aides), boosting their incentive and ability to seek out
work on their own at the end of the program.  The causal claim associated with this strategy is that
participation in a job-training program causes increased wages and labor force
participation after the program's end.  

In the 1970s the US government decided to find out if this strategy actually works as intended, and they
commissioned a large randomized experiment called the National Supported Work Demonstration.  ALmost 10,000
individuals --- primarily women who had previously been on government welfare, 
individuals recovering from drug addiction, individuals with criminal records, and 
young people without professional credentials --- were enrolled, and half(?) of them
were randomized to receive a job training opportunity, while thee others did not.


<!-- https://www.ojp.gov/pdffiles1/Digitization/59202NCJRS.pdf-->

## Covariates provide extra information about study participants

Here is a snippet of the data collected as part of this study

[INSERT datafraame]

Our previous discussion of experiments focused on two variables, the treatment 
and the outcome.  In this dataframe we can see both treatment (FILL IN) and outcome 
(FILL IN).  However, many other variables have clearly also been measured.  It 
is natural to ask why the government bothered collecting this data.  After all,
in a large randomized experiment you only need to know thrre treatment and the outcome
to get a reliable estimate of the ATE.


### Covariates give additional information about experimental subjects

List some covariates, mention pre-treatment.

### Comparing covariates across groups

Plots

**Standardized Mean Difference**

### Using probability to explain covariate balance



## Covariate balance as a tool for randomized experiments

Checking covariate balance is an important step for running reliable experiments
in practice.  It can help us catch administrative errors that occurred when
carrying out the experiment, and can flag situations where due to bad luck
our randomized groups are not as similar as we'd like.  

### Checking for administrative errors

(Reread Gerber and Green and bring in some detail, maybe some example.

Omnibus test?

### Correcting for chance imbalance using regression

What if we had just seen a single variable out of balance? This could happen even
if the experiment ran correctly, but is still concerning.

TOO MUCH?
In this case, a better way to estimate the average treatment effect is to fit 
a regression model with outcome, treatment, and any imbalanced variables.  The
coefficient of treatment will be a more reliable estimate.

## Natural experiments

NEW EXAMPLE

This is not technically a randomized experiment, since we didn't control or
choose how subjects received their treatments.  But it seems likely that
treatment was given in an arbitrary manner here. It is sometimes called a 
natural experiment or a quasi-experiment.
Can we use this data to
make judgments about a causal claim?

### Hypothetical experiments and covariate balance

A good place to start is to imagine that we had conducted an experiment.  What
would covariate balance look like?  We can compare the actual covariate balance
and run the same tests we did for the RCT above.  If the groups are sufficiently
well-balanced that we don't see a difference, it's easier to believe a claim.

WORK THROUGH DETAILS

### Limitations of covariate balance in natural experiments

MAYBE THIS GOES WITH MATCHING SLIDES>

In this example covariate balance helped us feel good about proceeding.  But
what if we'd measured three more variables and they'd all been really out of balance?
TRY TO MOTIVATE THIS MORE CLEARLY
In this case we probably wouldn't want to trust our results.


Of course, we didn't measure those variables, and we don't know for sure that
they weren't out of balance. One of the frustrating things about cases where we 
didn't perform the randomization ourselves is that we can never be sure we've measured 
all the important variables.



## Summary

FILL IN

[ ]{.column-margin}

<!-- [^scurvy]: This tale is recounted in full in "Scurvy, sailors, and science", Duncan P. Thomas in the Journal of the Royal Society of Medicine 1997; 90:50-54. -->

<!-- A future potential source of questions: -->
<!-- - what would a study look like if it did *not* have a control? (Queen Charlotte inoculating all of the prisoners in Newgate prison in London) what is the problem? -->
<!-- - what would a study look like if it were *not* randomized? (Lind's Scurvy Trials) -->
