---
title: "Lab 1: Getting Started"
author: "STAT 20 UC Berkeley, Spring '22"
output:
  xaringan::moon_reader:
    css: stat20.css
    lib_dir: assets/libs
    nature:
      highlightStyle: atelier-forest-light
      highlightLines: true
      highlightSpans: true
      ratio: 16:9
      countIncrementalSlides: false
      slideNumberFormat: "%current%"
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE,
                      echo = FALSE,
                      fig.align = "center",
                      fig.retina = 3)

library(tidyverse)
library(xaringanthemer)
source("https://raw.githubusercontent.com/stat20/course-materials/master/assets/stat20-style.r")
```

## Agenda 

- Icebreaker + Introduction (10 min) 
- Intro to Ed (5 min)
- Lab 1 Demo (10 min)
- Lab 1 Students (20 min)
- Q & A (5 min)

---
## Icebreaker
--

1. Write down 2 truths and a lie (1 min)

--

2. In breakout rooms of size 4, take turns sharing:
  - name
  - hometown
  - 2 truths and lie
  
--

3. After each student shares, group tries to guess which is the lie

---
## What is Stat 20 Lab?

.pull-left[
**Who**: 25-30 students + GSI

**What**: applying the concepts from lecture by working with real data  

**When**: Tu, Th mornings for 50 minutes  

**Where**: Initially Zoom, then 3rd floor Evans  
]

--

.pull-right[
**Why**: Doing statistics requires a synthesis of conceptual frameworks, ideas and notation from mathematics, computation tools, and an understanding of the context of the data. It's a complex task and it requires practice.  

**How**: When doing data analysis, for our computational tool we'll be using R.
]

---
class: center, middle

# Course Communication

Demo of Ed

---
## Edstem.org

Please

1. reply to the post with one true thing about yourself to share with the entire class,

2. like someone's post.


---
class: center, middle

# Writing and turning in Assignments in RStudio

Demo of RStudio and Gradescope

???
Students are shown
    - The four panels of RStudio, with a focus for now on files and editor.
    - How to create and save a new assignment Rmd.
    - How to knit to pdf, where the pdf shows up, and what the conceptual link is between source and final product.
    - Header vs Markdown
    - In the header, the following fields
        - title
        - author
        - output
    - In the markdown
        - normal text
        - headings
        - bold and italics
        - bulleted list
    ii. then left on their own to create their own document that answers a few questions (those question will show up only on the website as an html document).
    - How to download and submit their pdf to Gradescope.
