---
title: "Computing Probabilities"
format: stat20handout-pdf
---

Consider picking numbers from the following box.

\begin{center}
$\fbox{\fbox{0} \fbox{1} \fbox{2} \fbox{3}}$ $\hspace{1cm}$ 
\end{center}

Let $A$ be the event that the *first pick* yields an even number; $B$ be the event that the *second pick* is greater than or equal to one. 

@. Pick two numbers without replacement. Find $\text{P}(B|\text{first pick is 0})$.

\


@. Pick two numbers without replacement. Find $\text{P}(B|\text{first pick is 2})$.

\

@. Pick two numbers with replacement. Find  $\text{P}(B|A)$.

\


Consider a fair, eight-sided die. 

@. I roll the die four times. What is the probability that I roll the **same** number on all four rolls? 

\

\

@. I roll the die twice. What is the probability that the rolls are **different**?

\

\


<!---
Consider the events $A$ and $B$ which have probabilities $0.6$ and $0.5$ respectively, and we further have that $P(A \cup B) = 0.8$. 


@. Are $A$ and $B$ mutually exclusive? If not, what is $P(A \cap B)$?

\

\

@. What is the probability that *neither* $A$ *nor* $B$ will be true? Drawing a Venn diagram will be helpful here.

\

\
-->
  



My dog Bella has two toys that she loves: an orange ball, and a thick rope. Each time she picks out a toy, she chooses it independently of all the other times (like a coin toss). That day, she was busy, so went to her toys three times. 

Define the events $A$ and $B$ where:

$A$ is the event that she picked the rope *at most* one time; 

$B$ is the event that the toys she picked that day included *both* the rope and the ball.

@. Are $A$ and $B$ independent? *Hint: what is the relationship between mutually exclusive events and independent events?*

\newpage


An American roulette wheel has 38 pockets, of which 18 are red, 18 black, and 2 are green. In each round, the wheel is spun and a white ball lands in one of these 38 pockets.

@. What is the probability of getting at the ball landing in a green pocket at least once in 5 spins of the wheel?

\

\


A European roulette wheel has 37 pockets, of which 18 are red, 18 black, *and only 1 green*. The roulette wheel is numbered 0 through 36. 

@. Write R code to simulate three spins of this wheel. 

\

@. Now imagine that after each of the three spins, a pocket disappears. Simulate three spins of this magic wheel. 

\

We will now perform our first simulation of the year! For the following questions, consider the European roulette wheel of **Question 7** and ensure your Quarto document will present the same results each time it is rendered. Write your code in the spaces below.

@. Create three vectors: one which contains 100 simulated spins of the European roulette wheel (call this `one_hundred`), one which contains 1,000 such spins (call this `one_thousand`), and another which contains 10,000 such spins (call this `ten_thousand`). 

\

\

@. Create a new vector that returns `TRUE`/`FALSE` values for each element in `one_hundred`, where `TRUE` means that the number spun is greater than 18, and save it. Repeat these steps for the `one_thousand` and `ten_thousand` vectors.

\

\

@. Find the proportion of numbers spun in each simulation that were greater than 18 (write the code and the proportion). *Hint: how can you take a proportion of a logical vector?*

\

\

@. Comment on how the proportions changed with respect to the true probability of spinning a number greater than 18 as the number of spins increased. 

\

<!---

#### Question 4

Suppose $A$ and $B$ are non-empty events such that $P(A) = 0.5$ and $P(B) = 0.7$.  What is the smallest and biggest that their union, $P(A \cup B)$, and their intersection, $P(A \cap B)$, can be?

\


\

\

-->

<!---

#### Question 5 The Paradox of Chevalier de Méré

Antoine Gombaud, the self-styled Chevalier, lived in the 17th century and liked to gamble on the outcomes of die rolls. One game that he was fond of involved betting money on getting at least one six in 4 rolls of a fair six-sided die. We know that he computed this probability as $\displaystyle \frac{1}{6} +  \frac{1}{6} +  \frac{1}{6} +  \frac{1}{6} =  \frac{2}{3}$. 

(a) We discussed how this is incorrect, but what is the *correct* probability of getting at least one six in 4 rolls of a fair die?

\

\

(b) Another game that he used to play was betting on rolling a pair of sixes at least once in 24 rolls of a pair of fair six-sided dice. He computed this probability as $\displaystyle 24 \times  \frac{1}{36} =  \frac{2}{3}$. This is also incorrect. What is the correct answer?
\

\

-->

<!--

#### Question 6 Chance of having H1N1

 It was established that the H1N1 (swine flu) pandemic of 2009 originated in pigs from a very small region in central Mexico. Early cases in the US were associated with recent travel to Mexico. Say at that time, a college student went to Mexico and let’s assume that at the time, the rate of infection for travelers to Mexico was 1 in 1,000. Let’s suppose that the test for H1N1 has 99% accuracy. That is the chance of a false positive  is 1% and the chance of a false negative is also 1%. If a person has a positive test result, what is the chance that they truly have H1N1? You can work it out using conditional probabilities and Bayes' rule, or just approximate this probability using a heuristic argument as in the slides.

-->



