---
title: Configuring this Website
---

## Design

One repo to rule them all.

### Principles

1. Organization: files should be organized in a way that prioritizes thinking of it as a curriculum (instead of a website or a series of assignments). (subpoint: modularity)
2. Reproducibility:
3. Documentation:
4. Automation: automate as many non-human tasks as possible.

## Contributing

### Configuring your machine

1. On your machine, a new RStudio project from version control, linked directly to the repo at <https://github.com/stat20/stat20>.
2. Be sure you've [configured git](https://happygitwithr.com/hello-git) on your machine (allowing you to make commits) and [stored a Personal Access Token](https://happygitwithr.com/https-pat) (PAT) (allowing your machine to push commits to your repo on GitHub).

### Workflow

1. In RStudio on `main`, pull any new changes.
3. Create a new branch named with what you're adding, prepended with your name (e.g. `andrew-update-lab-6`).
4. Edit the files you wish to work on. As you go, the easiest way to see how your changes look is to run `quarto preview --profile staff-site` at the terminal. That will do a minimal render of the website to show you the document that you're working on and will re-render that document every time you save. You can also run `quarto preview` if you want to see the student-facing site (with no staff guide).
5. Commit your changes to your new branch and push them to GitHub.
6. Go to your GitHub and make a pull request from your new branch into `stat20/stat20`, `main` branch. Once the PR is made, it will kick-off a test rendering of both the student site and the staff site (the staff site will take > 10 min to fully render). Once they're done, you can go to <https://stat20-pr.netlify.app/> and <https://stat20staff-pr.netlify.app/> to see how they look. Note: this action will kickoff anew for each commit that you add to the PR, so it can be good to make the PR when you have just one commit on the branch, then check back as you push more commits to see how it looks.
7. Once the PR is merged into `main`, it will kick-off an action that will render and publish the staff site to <https://stat20staff.netlify.app/>. <https://stat20.org/> doesn't get rendered and published when `main` is changed, but instead of a pre-programmed schedule. After merging the branch, that branch can be deleted.

### Adding a page

1. Create a new qmd file
2. Add your content like normal


### Course Settings {#course-settings}