on:
  workflow_dispatch:
  pull_request:
    branches: next-semester
  
name: "Publish to stat20-next-semester.netlify.app"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # for accessing this repo's assets in the container
      - name: Check out the repo
        uses: actions/checkout@v3
      # run the container, attaching this repo as a working directory
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        env:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          image: stat20/stat20-docker:latest
          options: -v ${{ github.workspace }}:/home/rstudio/stat20 -e NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }}
          shell: bash
          run: |
            # exit if any command returns non-zero exit
            set -e

            # execute from the textbook
            cd /home/rstudio/stat20/

            # _freeze should not exist
            rm -rf ./_freeze
            
            # run pre-render scripts
            Rscript ./assets/scripts/propagate-dates.r
            Rscript ./assets/scripts/homepage-readings.r
            Rscript ./assets/scripts/ignore-future-docs.r
            Rscript ./assets/scripts/write-toc.r
            
            # render site and upload to stat20-next-semester.netlify.app
            quarto publish netlify --id 71793655-483e-4d50-aec7-de1381435888
